### ISSUE TITLE
Проксі

### ISSUE THREAD

**Issue by PXEiYyMH8F** [porthole-ascend-cinnamon/mhddos_proxy#10]
[Forwarded from DDOS по країні СЕПАРІВ (Кібер-Козаки)]
Друзі, публікуємо веб-ресурси на яких можна отримати безкоштовні проксі! 
https://raw.githubusercontent.com/clarke...st-raw.txt 
https://api.proxyscrape.com/v2/?request=...nymity=all 
https://api.proxyscrape.com/ v2/?request=...country=all 
https://api.proxyscrape.com/v2/?request=...ountry=all 
http://hack-hack.chat.ru/proxy/anon.txt 
http ://hack-hack.chat.ru/proxy/p1.txt 
http://hack-hack.chat.ru/proxy/p2.txt 
http://hack-hack.chat.ru/proxy/p3.txt 
http://hack-hack.chat.ru/proxy/p4.txt 
https://multiproxy.org/txt_all/proxy.txt 
http://spys.me/proxy.txt 
https://raw.githubusercontent.com /Shifty...r/http.txt 
https://raw.githubusercontent.com/Shifty.../https.txt 
https://raw.githubusercontent.com/Shifty...socks4.txt 
https://raw.githubusercontent.com/Shifty...socks5.txt 
https://raw.githubusercontent.com/clarke...y-list.txt 
https://www.sslproxies.org/ 
https:// www.google-proxy.net/ 
https://free-proxy-list.net/anonymous-proxy.html 
https://free-proxy-list.net/uk-proxy.html 
https://www.us- proxy.org/ 
https://free-proxy-list.net/ 
https://www.socks-proxy.net/ 
https://premproxy.com/list/ip-port/1.htm 
https://premproxy .com/list/ip-port/2.htm 
https://premproxy.com/list/ip-port/3.htm 
https://premproxy.com/list/ip-port/4.htm 
https:// premproxy.com/list/ip-port/5.htm 
https://premproxy.com/list/ip-port/6.htm 
https://premproxy.com/list/ip-port/7.htm 
https://premproxy.com/list/ip-port/8.htm 
https://premproxy.com/list/ip-port/9.htm 
https://premproxy.com/list/ip-port/10. htm 
https://premproxy.com/list/ip-port/11.htm 
https://premproxy.com/list/ip-port/12.htm 
https://premproxy.com/list/ip-port/13 .htm 
https://premproxy.com/list/ip-port/14.htm 
https://premproxy.com/list/ip-port/15.htm 
https://premproxy.com/list/ip-port/ 16.htm 
https://premproxy.com/list/ip-port/17.htm 
https://premproxy.com/list/ip-port/18.htm 
https://premproxy.com/list/ip-port /19.htm 
http://proxydb.net/ 
https://proxypremium.top/full-proxy-list 
https://premiumproxy.net/full-proxy-list 
https://proxypremium.top/elite-proxy- список 
https://proxypremium.top/http-proxy-list 
https://proxypremium.top/https-ssl-proxy-list 
https://proxypremium.top/socks-proxy-list 
http://www.freeproxy.ru /download/lists/goodproxy.txt 
https://hidemy.name/de/proxy-list/ 
https://spys.one/en/free-proxy-list/ 
https://free-proxy-list.com/ 
https://www.proxynova.com/proxy-server-list/ 
https://advanced.name/freeproxy 
https://geonode.com/free-proxy-list 
https://www.proxy-list.download/ HTTP 
https://www.proxydocker.com/ 
https://www.proxy-list.download/SOCKS4 
https://www.proxy-list.download/SOCKS5 
https://premiumproxy.net/ 
https://www .netzwelt.de/proxy/index.html 
https://proxyservers.pro/

**Comment by porthole-ascend-cinnamon** [comment]
Дякую, я бачив цей список, ніби додавав, але перегляну ще раз.

**Comment by porthole-ascend-cinnamon** [comment]
Так, я згадав. Справді, з цього списку є немало нових джерел, але усі вони або мають або хоч якийсь захист від скачування (що простий запит не проходить, треба якісь заголовки абощо), або мають не підходящий формат (парсер очікує знайти ip:port як єдину строчку, а також однотипні проксі в таблиці, а не в перемішку). 
Це все можна реалізувати, але потребує немало часу. Ідеальний варіант - написати окремий парсер, і надати одне посилання на файл що агрегуватиме унікальні проксі з цих серверів, і оновлюватиме їх періодично. Якщо маєте можливість - буду радий прийняти пулл реквест або посилання на такий файл.

**Comment by metaborsch** [comment]
What about using https://github.com/constverum/ProxyBroker?

**Comment by porthole-ascend-cinnamon** [comment]
@metaborsch я його бачив, дякую, але не уявляю куди і як його прикручувати. Хіба що з нього списки витягнути

**Comment by porthole-ascend-cinnamon** [comment]
Деякі джерела зі списку було додано.

**Comment by porthole-ascend-cinnamon** [comment]
Переглянув усе, що можливо - буде додано в наступних версіях
