### ISSUE TITLE
Downscale processing when target is "dead"

### ISSUE THREAD

**Issue by 0xffiber** [porthole-ascend-cinnamon/mhddos_proxy#104]
Async version only.

The scheduler performs upscale by starting with relatively low number of coroutines and "forking" them on successful connection to the target. This approach helps to dynamically allocate more resources to those cases where the attack actually does something. But there's another side of the coin: if the target died after the upscale phase is over the system is going to keep more coroutines dedicated to it than it's necessary. There should be a way for the scheduler to decide that the resources allocated to the specific target need to be re-allocated for something else.

The detailed discussion of the algorithm is absolutely required before implementation (downscale is typically a much more complex problem than upscale).

**Comment by porthole-ascend-cinnamon** [comment]
As a quick solution - what if we always re-install targets with certain interval (when reloading), effectively restarting the upscale phase and allowing algorithm to re-balance itself?

**Comment by porthole-ascend-cinnamon** [comment]
Kinda solved? Allocation is reset every 5 minutes allowing upscale algorithm to re-balance itself

**Comment by porthole-ascend-cinnamon** [comment]
Assuming solved
