### ISSUE TITLE
Temporarily deprioritize dead proxies

### ISSUE THREAD

**Issue by 0xffiber** [porthole-ascend-cinnamon/mhddos_proxy#105]
As of now, the system takes proxies from the pool randomly. Even when there's enough evidence that the proxy is dead (a lot of unsuccessful attempts to connect).

Similarly to dynamic resource allocation for targets, it would be beneficial to have dynamic allocation of proxies from the pool. At least a way to temporarily mark  proxy as "dead" after N unsuccessful attempts to establish TCP connection to it (note, this doesn't mean unsuccessful connection to the target as there are a lot of reasons that one might fail even with perfectly healthy proxy). In async version tracking of open TCP connections doesn't require any sort of synchronization between threads thus could be performed without losing effectiveness of the attack. 

The detailed discussion of the algorithm is required before implementation.

**Comment by yuchdev** [comment]
I see a connection with #102 here: saving the application stats in a database would help to range proxies dynamically by a variety of criteria, and at the same time serve these stats as REST API service

**Comment by porthole-ascend-cinnamon** [comment]
Not viable
