### ISSUE TITLE
Configuration for IP-based target with custom Host header

### ISSUE THREAD

**Issue by 0xffiber** [porthole-ascend-cinnamon/mhddos_proxy#106]
As of now the configuration supports only 2 options:
* the target is given as IP address
* the target is given as host (DNS is resolved on each targets update)

The downside of using IP address is that that system cannot set proper Host header for L7/HTTP attacks. The proposed solution to the problem would be new optional `host` param in the configuration file:

```
http://127.0.0.1:8080 GET                            # host header = 127.0.0.1:8080
http://localhost:8080 GET                           # dns resolve on config update, host header = localhost:8080
http://127.0.0.1:8080 GET host=not-localhost.com    # host header =  not-localhost.com
```

**Comment by FluxState** [comment]
have you dropped this feature? is there any other solution than either this or reverting to socket + /etc/hosts?

**Comment by porthole-ascend-cinnamon** [comment]
@FluxState you can use uncodumented config file params
`http://not-localhost.com GET ip=127.0.0.1`
