### ISSUE TITLE
aarch64 linux/arm64 image failed to start

### ISSUE THREAD

**Issue by rnd49** [porthole-ascend-cinnamon/mhddos_proxy#117]
Environment:
Linux Ubuntu 22.04 LTS aarch64
Docker version 20.10.16, build aa7e414
`docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy`
```
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:a162428484f65932ee898d3303c52e83f5dd8833a5cc09c9aef06e2d2ec9fe75
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 12, in <module>
    from src.cli import init_argparse
  File "/mhddos_proxy/src/cli.py", line 8, in <module>
    from .mhddos import Methods
  File "/mhddos_proxy/src/mhddos.py", line 19, in <module>
    from OpenSSL import SSL
  File "/mhddos_proxy/dependencies/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/mhddos_proxy/dependencies/OpenSSL/crypto.py", line 8, in <module>
    from cryptography import utils, x509
  File "/mhddos_proxy/dependencies/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/mhddos_proxy/dependencies/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: Error relocating /mhddos_proxy/dependencies/cryptography/hazmat/bindings/_rust.abi3.so: unsupported relocation type 7
```

**Comment by alexnest-ua** [comment]
Unfortunately, this problem cannot be solved as quickly as we would like, so for now please use the installation directly: https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/main/docs/installation.md#linux

**Comment by porthole-ascend-cinnamon** [comment]
I don't see this build neither in tagged nor in un-tagged versions https://github.com/users/porthole-ascend-cinnamon/packages/container/mhddos_proxy/versions . Can you try removing you image and pulling the latest again?

**Comment by rnd49** [comment]
same for new build
`docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy`
```latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:335f1dcedf46ffc081cafce766739a824c63491b087d7272f57271c9af36f954
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 13, in <module>
    from src.cli import init_argparse
  File "/mhddos_proxy/src/cli.py", line 8, in <module>
    from .mhddos import Methods
  File "/mhddos_proxy/src/mhddos.py", line 19, in <module>
    from OpenSSL import SSL
  File "/mhddos_proxy/dependencies/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/mhddos_proxy/dependencies/OpenSSL/crypto.py", line 8, in <module>
    from cryptography import utils, x509
  File "/mhddos_proxy/dependencies/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/mhddos_proxy/dependencies/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: Error relocating /mhddos_proxy/dependencies/cryptography/hazmat/bindings/_rust.abi3.so: unsupported relocation type 7
```

<img width="732" alt="image" src="https://user-images.githubusercontent.com/26868471/169042547-4a2a3b21-9ca8-43d3-97f2-1e3e4e767bef.png">

**Comment by porthole-ascend-cinnamon** [comment]
Yes, for some reason it doesn't want to cross-build for arm64 from amd64 machine

**Comment by avoylenko** [comment]
I have the same issue, can't run the docker image on Raspberry Pi 4 neither on MacBook with M1 processor.

**Comment by porthole-ascend-cinnamon** [comment]
I think I've figured it out, at least the error is gone on mine M1 mac. Can you verify?

**Comment by avoylenko** [comment]
Thank you. Now it works on M1, but there is still a problem to run it on RPI:
`
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:75dd6868f8c47ae52977127766f849a88d4bcdf90ab3b3203a763faae0f501b7
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
exec /opt/venv/bin/python3: exec format error
`

**Comment by porthole-ascend-cinnamon** [comment]
@avoylenko did it work before?

**Comment by avoylenko** [comment]
I have no idea, I just tried a few hours ago

**Comment by porthole-ascend-cinnamon** [comment]
I see. Can you try  `docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy@sha256:b6102ea345077d6c2208a7048ee713fdc762041641b6bf287f0c8c9c15bed924` ?

**Comment by avoylenko** [comment]
You are awesome, that image works on RPi 4 board

**Comment by rnd49** [comment]
#121

**Comment by porthole-ascend-cinnamon** [comment]
@avoylenko it's an old image, unfortunately

**Comment by porthole-ascend-cinnamon** [comment]
Can you folks try this one?
`docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:beta`

**Comment by avoylenko** [comment]
@porthole-ascend-cinnamon 
**M1** - works
**RPi4** - works

Can't test it on amd64 arch

**Comment by porthole-ascend-cinnamon** [comment]
Great, thanks a lot! Works for me on amd64. Will push to :lastest
