### ISSUE TITLE
Use runner.py as C2 console

### ISSUE THREAD

**Issue by yuchdev** [porthole-ascend-cinnamon/mhddos_proxy#128]
I have one more idea to offer.

Some MHDDoS users probably have the whole botnet network in their possession.

What if we think about how to launch (and stop) the attack of the whole botnet from just one console command.

Commands are being sent to nodes by SSH, so we have two major requirements:

* The host with the C2 runner script should have SSH keys to access all nodes
* `runner.py` on every single node should be added to `$PATH` or located by some expected path 

The command launching the attack from the whole botnet may look like:

`python3 runner.py --node root@123.45.67.88 --node user@23.45.56.78 --node ubuntu@aws-12-34-56-78.com --itarmy`

Feel free to discuss 🙂

**Comment by 0xffiber** [comment]
Hey @yuchdev! Regarding 

> how to launch (and stop) the attack of the whole botnet

I assume you can do so right now with the help of any tool that provides "parallel SSH" functionality as you only need to execute the same shell command on all machines (there's no coordination happening between machines).

**Comment by yuchdev** [comment]
You're right, this task is out if the application scope
