### ISSUE TITLE
Not real traffic speed is showed in console

### ISSUE THREAD

**Issue by Geniy00** [porthole-ascend-cinnamon/mhddos_proxy#132]
1. In my opinion, the traffic speed that is showed with `--debug` flag doesn't look real. It hard to prove it, but please look at my screens

![photo5213335264024444161](https://user-images.githubusercontent.com/1192251/169761909-cbc1daba-c95d-44c1-9f85-208ff584ac0d.jpg)
It showed the traffic ~4.84 Mbit/s at that moment

you could see that VPN connection was setup only 7 mins ago and it showed 690MB downloaded and >1GB uploaded. I didn't run any additional applications that could download any content.

The screenshot below shows speed in web interface of my router. The speed was > 25 Mbps/s

![image](https://user-images.githubusercontent.com/1192251/169762518-64293038-3b59-4c80-b3fd-c463940c60f5.png)

In my opinion, there is wrong calculation of the speed. I could see a situation that it shows 0 (after 30-60 mins of working), but in router console it was about 20-40mbps/s, and when I stop VPN and mhddos_proxy it shows the speed about 0 in router.

2. According to my checks I think that `--debug` and `--table` affect performance of the application. 
On the screen below you could see the second run without `--debug` flag. I reconnected VPN again, and it could connect to another server that has less load, but I could see the same situation every time I did this test.
Probably you execute additional calculations only for  `--debug` or you print too many logs that could affect performance as well. I would double check the code, because I think it degrades performance very much 

![image](https://user-images.githubusercontent.com/1192251/169763465-49e04ea2-a6b0-4e3f-952b-62d72f8de6ba.png)

**Comment by porthole-ascend-cinnamon** [comment]
That's highly possible that you'll see different measurements on different levels/devices, due to the buffering and other mechanisms. The script counts what it was able to send to the syscall. We'll review the code for some apparent miscalculations.

As for the debug mode - currently working on making it unnecessary, calculations does not look very complex but we'll try to optimize some of it. How much `-t` are your running? Do you maybe get "Зафіксована затримка у виконанні операцій" warning?

**Comment by porthole-ascend-cinnamon** [comment]
New no-debug-needed version is out - give it a try!

**Comment by Geniy00** [comment]
I checked shows the speed with TaskManager which shows almost the same speed as my router web console, and I think it looks good now. mhddos_proxy shows upload speed almost the same as taskmanager

I'd like to ask one more question in this thread:
Do you know why we have different speeds in docker and on a windows machine? How to get the highest performance?

you could see 4 different intervals of attack speed
![image](https://user-images.githubusercontent.com/1192251/170888736-1c4e3d51-5e33-42ad-b365-490747acddb2.png)
1, 3 - I run python script on a windows 10 without docker `git pull && pip install -r requirements.txt && python runner.py --itarmy -t 4000 --copies 2 --vpn`. I got the highest performance with 3000-4000 threads. thread 10000 degrade performance

2, 4 - docker compose on windows 10 with WSL2. I used the same arguments `--itarmy -t 4000 --copies 2 --vpn`

1 copy with 8000 threads has worse performance than my `-t 4000 --copies 2`

I think updating documentation with performance diagrams and recommending the users to check different configurations can help them to be more effective.

**Comment by snegurok** [comment]
I guess this ticket may be closed, as Geniy admitted he sees the correct numbers now. And I see the same. However one needs to know, that **only upload traffic is accounted in mhddos output**. Don't think it's documented. But now at least this ticket documents it :)

**Comment by baragoon** [comment]
Looks like that mhddos output traffic is a total outgoing traffic on the server. For example, when only mhddos is running - output is 10mbps. BUT, run speedtest-cli in the inifinite loop and mhddos traffic showing 100+ mbps.
So when not only mhddos generating outbound traffic this counters are totally incorrect.
