### ISSUE TITLE
Targets double count?

### ISSUE THREAD

**Issue by KarboDuck** [porthole-ascend-cinnamon/mhddos_proxy#139]
Seems like latest version (may 25) double count targets . Possibly if two methods (GET and STRESS) choosed it counts them like different targets when displaying stats.

Info from config file:
![image](https://user-images.githubusercontent.com/53382906/170237957-5809b927-d461-4c7b-ab16-be4da65d2368.png)

Info from output:
![image](https://user-images.githubusercontent.com/53382906/170237671-c3cf4b5c-82dc-4703-abf0-fe2bd1e65811.png)

**Comment by porthole-ascend-cinnamon** [comment]
Yes, that is correct, it counts distinct "flooder tasks" which is targets * methods that is displayed in the beginning of the attack.
We can probably count unique domains/ips from the set of the flooders, but there is still a weird case when you set a low number of threads (you will then have 3 different numbers for the "targets count'). 
Thanks for the report.

**Comment by porthole-ascend-cinnamon** [comment]
There is no consensus on how this should work, so I've removed the `Targets: 1030` (temporary?)

**Comment by porthole-ascend-cinnamon** [comment]
No further changes
