### ISSUE TITLE
pull access denied for portholeascend/mhddos_proxy, repository does not exist or

### ISSUE THREAD

**Issue by su-hs** [porthole-ascend-cinnamon/mhddos_proxy#14]
So you removed latest published version?

https://hub.docker.com/search?q=portholeascend%2Fmhddos_proxy%20&type=image

have you renamed maybe?

**Comment by localdotcom** [comment]
Seems like it has been deleted from docker hub.
You can use this one dclocal/mhddos_proxy

**Comment by su-hs** [comment]
@localdotcom who are you? Where is @porthole-ascend-cinnamon ? :) I start panicking...

**Comment by porthole-ascend-cinnamon** [comment]
Я тут. Аккаунт на DockerHub видалили без повідомлення. Скоро буде перезалив кудись. Будь ласка, не користуйтеся сторонніми репозиторіями, ми не можемо знати що в них.

**Comment by localdotcom** [comment]
I faced the same issue when tried to pull image and pushed built image to my docker hub account

**Comment by porthole-ascend-cinnamon** [comment]
ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
Новий репозиторій, README оновлено.
