### ISSUE TITLE
STRANGE OBFUSCATED CODE

### ISSUE THREAD

**Issue by PerchunPak** [porthole-ascend-cinnamon/mhddos_proxy#142]
# STRANGE OBFUSCATED CODE

There is few strange files with **obfuscated** data in.
- [`src/vendor/load_proxies.py`](https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/537695e6c8a2a2b5123e9ec7724f0be4c41fcef2/src/vendor/load_proxies.py) - Closed source private proxy system. **Possible** safe. [Details.](#load_proxies.py)
- [`src/vendor/refers.py`](https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/537695e6c8a2a2b5123e9ec7724f0be4c41fcef2/src/vendor/refers.py) - List with refers. **Safe**. [Details.](#refers.py)
- [`src/vendor/rotate.py`](https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/537695e6c8a2a2b5123e9ec7724f0be4c41fcef2/src/vendor/rotate.py) - Prevent attacks to `.ua` sites. **Safe**. [Details.](#rotate.py)
- [`src/vendor/useragents.py`](https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/537695e6c8a2a2b5123e9ec7724f0be4c41fcef2/src/vendor/useragents.py) - User Agents list. **Safe**. [Details.](#useragents.py)

## Steps to deobfuscate code

This steps identical for all files, mentioned upper.
- Use `black` on files, so they will be more human-readable.
- Copy all content, except last line, to interpreter (command `python` without arguments).
- Instead of last line, paste:
```python
with open("file_which_deobfuscating.py", "wb") as f:
    f.write(base64.b64decode(eval("BYTES FROM ORIGINAL LINE HERE")))
```
- Repeat this few times, if you get obfuscated code like in first time again. Note that this all need to do in one interpreter session, restart interpreter only on next file.
- See additional info in [details](#details) section.

### load_proxies.py

This is closed source private proxy getter. Some info about it found in 7e8af709836053cf1fd693ebd4a749bc5305d24d:
```md
<!-- file README.md -->
### ⏱ Останні оновлення

+- **09.04.2022** Нова система проксі - тепер кожен отримує ~200 проксі для атаки з загального пулу ~6000 штук. Параметри `-p` (`--period`) та `--proxy-timeout` більше не використовуються
...
<!-- translated to english -->
### ⏱ Last updates

+- **09.04.2022** New proxy system - now everyone gets ~200 proxies for attack, from total amount of ~6000 items. Parameters `-p` (`--period`) and `--proxy-timeout` no more used
...
```
So it is decrypt info from GitHub [proxy_scraper](https://github.com/porthole-ascend-cinnamon/proxy_scraper) repository, and cut list of proxies to 200 items.

Also, this full of trash code and additionally obfuscated with https://pyob.oxyry.com (maybe also used more obfuscators, no matter). There is no way deobfuscate code more, even PyDeobfuscator generate invalid trash.

The algorithm of decryption really strange (of course, it is obfuscated), but on first look, it is safe to use. Also, with debugger, you can steal all ~27465 proxies (from one random file).

Small script on 31 lines with some monkeypatching gives me ~102477 proxies. Of course I will not post it here.

#### Conclusion

I haven't much time to fully investigate this code, but on first look it is okay. Anyway, I hate when on open source project, there is some closed source part. People must know what they download, and get full access to code, if it open source. This is the reason why I am writing it here.

### refers.py

Just a list with refers, obfuscated because of possible fast fix for attacks from site owners.

### rotate.py

Original code:
```python
from yarl import URL

suffix = '\x2E\x75\x61'  # .ua

params = [
    (URL('https://profile.sber.ru'), '84.252.144.102'),
    (URL('https://3dsec.sberbank.ru'), '62.76.205.110'),
    (URL('https://cdek.ru'), '178.248.238.208'),
    (URL('https://lk.platon.ru'), '83.169.194.22'),
    (URL('https://auth.kontur.ru'), '46.17.206.15'),
]
```
Which will be later used as:
```python
# src/mhddos.py
from .vendor.rotate import params as rotate_params, suffix as rotate_suffix
...
def parse_params(url, ip, proxies):
    result = url.host.lower().endswith(rotate_suffix)
    if result:
        return random.choice(rotate_params), NoProxySet
    return (url, ip), proxies
```
This just check is target ends with `.ua` and if it is, then it will choose random target from `params` list.

### useragents.py

Just random user agents list.

# CHECK THIS YOURSELF

You free to check every what I wrote here, and I would be happy if you do. I wrote every step for getting original code, even more.

**Comment by porthole-ascend-cinnamon** [comment]
I appreciate you effort, but this can seriosly hurt UA IT Army, so I'll have to delete this. #StandWithUkraine

**Comment by PerchunPak** [comment]
I did, but people really should know what they using.

**Comment by porthole-ascend-cinnamon** [comment]
Sure, also enemies should steal all proxies and use them against us, great idea to help Ukraine win the war.

**Comment by alexnest-ua** [comment]
> I did, but people really should know what they using.

Hey, man. Just answer me these questions, please:
1) We reaaly have a database of ~30,000 working proxies, most of which were purchased by us personally. Do we need to make the database public so that any stupid Russian schoolboy can resell it and earn money and pay taxes in Russia that will go to war?
2) Do you think we must let attacking .ua site by program written by Ukrainian developers?
3) Do you think that we are doing incorrect things, so you decided to "expose" us?

**Comment by PerchunPak** [comment]
> We reaaly have a database of ~30,000 working proxies, most of which were purchased by us personally. Do we need to make the database public so that any stupid Russian schoolboy can resell it and earn money and pay taxes in Russia that will go to war?

You don't need do this. I just saw obfuscated code, and wanted know what in it. Also your repository returns ~100k proxies, as I mention before. I wouldn't leak them, or something like it, just wanted to people know, is this code really safe.

> Do you think we must let attacking .ua site by program written by Ukrainian developers?

No, of course not. I didn't mention anywhere my opinion about code in this files, but also, I doesn't understand why is it closed. I understand why `refers.py` and `useragents.py` closed (actually, they can be also open, because russian sites can't just block all listed user agents/referrers, this doesn't give anything in real), but `rotate.py` - no. It is fully okay to just hardcode this, and raise error when someone trying attack Ukrainian sites.

And `.ua` domain can buy anyone, actually there is few Ukrainian sites sponsored by russia.

---

[if you allow...](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue)
