### ISSUE TITLE
Scale up mhddos_proxy automatically in order to utilize all system resources

### ISSUE THREAD

**Issue by kirealll** [porthole-ascend-cinnamon/mhddos_proxy#145]
It would be good if you introduce the ability to scale up mhddos_proxy (increase copies and threads parameters) automatically in order to utilize all system resources or up to the predefined threshold. Similar logic is already implemented in DB1000NX100. It scales up step by step measuring the average CPU and memory usage until it reaches the predefined limits. 

mhddos_proxy is used on many virtual machines, but by default, it utilizes limited resources. For example, I created the cheapest VM in Digital Ocean and allowed IT Army to start there attacks via Telegram bot @gov_ddos_ru_bot. But my simple VM is utilized only by 20%. So, the attack on my server can be easily increased in 4-5 times.  Let's utilize all our resources more efficiently and make our attacks more powerful.

The application should restart the scale-up after each target update because different sets of targets require different system resources.

**Comment by porthole-ascend-cinnamon** [comment]
Added `--copies auto` option which would select the copies based on the number of CPU available. Our tests has shown that 1 copy per CPU is optimal value. If you have the cheapest machine, it has something like 0.5 vCPU, and looking at just cpu utilization is bad metric - you will be throttled if you go too high. 1 copy with 1000 threads is this machine max.
 
If you tests show something different, please provide all the spec, examples of the commands which increase the network traffic and some screenshots.

**Comment by kirealll** [comment]
Thanks for picking up this enhancement ticket. However, I don't quite understand the effect of the `--copies auto` option. On one of the cheapest Digital Ocean servers with 1 vCPU and 2 GB of RAM I started mhddos_proxy with default parameters `runner.py --itarmy --copies auto`, but the server's resources were quite far from full utilization:

![image](https://user-images.githubusercontent.com/49598577/172822269-bb3aedfd-1aa4-403f-984d-ce97df98c757.png)

![image](https://user-images.githubusercontent.com/49598577/172822701-358a1e24-4f7f-4e2e-864f-60196f61945e.png)

**Comment by OlegYch** [comment]
@porthole-ascend-cinnamon F1s worked fine for a day
perhaps it would be faster to just adjust the bot and allow passing number of threads via the csv file?

**Comment by kirealll** [comment]
@porthole-ascend-cinnamon I believe you know better what needs to be done to scale up mhddos_proxy, whether it's increasing copies or threads. The main idea is that it should be done automatically. There are many people who are not good in IT, but would like to contribute to our cyber attacks. So, they create simple free VM's on DO, GCP or AWS by following tutorials from itarmy.com.ua. Then they hand over the access to these servers to Telegram bot @gov_ddos_ru_bot. But the attacks started via the bot are inefficient, because they don't utilize all VM's resources. 
@OlegYch unfortunately your proposal won't solve the problem, because it requires IT knowledge to determine the optimal number of threads for every server.

**Comment by porthole-ascend-cinnamon** [comment]
We've changed the number of threads for single-core machines from 1000 to 4000 - that should provide a significant boost and (hopefully) nothing breaks on most VPS. We'll restart the servers from @gov_ddos_ru_bot soon

**Comment by OlegYch** [comment]
hm with `docker run --rm -d --pull always --entrypoint ./runner.sh ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest python3 --itarmy` i get
```
[21:40:06 - INFO] Усього: З'єднань: 37, Запити: 5.25k/s, Трафік: 39.35 MBit/s
[21:40:11 - INFO] Усього: З'єднань: 49, Запити: 3.33k/s, Трафік: 23.61 MBit/s
[21:40:16 - INFO] Усього: З'єднань: 50, Запити: 4.15k/s, Трафік: 30.19 MBit/s
[21:40:21 - INFO] Усього: З'єднань: 54, Запити: 2.67k/s, Трафік: 18.50 MBit/s
[21:40:26 - INFO] Усього: З'єднань: 62, Запити: 4.81k/s, Трафік: 33.86 MBit/s
[21:40:31 - INFO] Усього: З'єднань: 68, Запити: 5.97k/s, Трафік: 42.81 MBit/s
[21:40:36 - INFO] Усього: З'єднань: 83, Запити: 6.42k/s, Трафік: 49.32 MBit/s
[21:40:41 - INFO] Усього: З'єднань: 102, Запити: 7.39k/s, Трафік: 55.34 MBit/s
[21:40:46 - INFO] Усього: З'єднань: 99, Запити: 6.96k/s, Трафік: 51.40 MBit/s
[21:40:51 - INFO] Усього: З'єднань: 125, Запити: 5.06k/s, Трафік: 41.03 MBit/s
[21:40:56 - INFO] Усього: З'єднань: 125, Запити: 5.57k/s, Трафік: 40.37 MBit/s
[21:41:01 - INFO] Усього: З'єднань: 124, Запити: 4.16k/s, Трафік: 30.35 MBit/s
[21:41:06 - INFO] Усього: З'єднань: 130, Запити: 4.78k/s, Трафік: 35.44 MBit/s
[21:41:11 - INFO] Усього: З'єднань: 128, Запити: 6.52k/s, Трафік: 52.17 MBit/s
[21:41:16 - INFO] Усього: З'єднань: 131, Запити: 7.05k/s, Трафік: 53.12 MBit/s
[21:41:21 - INFO] Усього: З'єднань: 123, Запити: 7.34k/s, Трафік: 51.56 MBit/s
[21:41:26 - INFO] Усього: З'єднань: 106, Запити: 6.62k/s, Трафік: 47.78 MBit/s
[21:41:31 - INFO] Усього: З'єднань: 119, Запити: 6.49k/s, Трафік: 47.47 MBit/s
[21:41:36 - INFO] Усього: З'єднань: 117, Запити: 4.36k/s, Трафік: 33.40 MBit/s
```
and adding more threads with -t doesn't improve the bandwidth like it used to
so with latest command from the bot i get two times less bandwidth on single-core vm, compared to `docker run --rm -d --pull always --entrypoint ./entrypoint.sh ghcr.io/0xffiber/mhpside:ubuntu-latest-qa --proxies http://localhost:9282/proxies.txt --itarmy --copies auto -t 10000`:
![image](https://user-images.githubusercontent.com/268312/173206327-bdf3b0ae-abd6-4e33-86bc-2b714f1668ee.png)

not sure what changed...

**Comment by OlegYch** [comment]
scratch that, -t works
so 4000 is way low for azure F1s
10000 and even 20000 works much better

**Comment by kirealll** [comment]
Utilization of the cheapest VM (1 vCPU and 1 GB of RAM) on DO, delegated to @gov_ddos_ru_bot, was significantly improved:

![image](https://user-images.githubusercontent.com/49598577/173246278-ed7e7dde-3897-46c2-a4c8-651221916a73.png)

![image](https://user-images.githubusercontent.com/49598577/173246375-e073957a-004d-47cf-80b4-0af5bc709e82.png)
