### ISSUE TITLE
Не виходить запустити через докер після зміни ghcr.io

### ISSUE THREAD

**Issue by ariangryfx** [porthole-ascend-cinnamon/mhddos_proxy#16]
Не виходить запустити через докер після зміни ghcr.io
- раніше з portholeascend/mhddos_proxy працювало добре
- Після викоритання ghcr.io/portholeascend/mhddos_proxy:
Unable to find image 'ghcr.io/portholeascend/mhddos_proxy:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/portholeascend/mhddos_proxy/manifests/latest": denied.
- Після docker login:
Unable to find image 'ghcr.io/portholeascend/mhddos_proxy:latest' locally
docker: Error response from daemon: manifest unknown.

**Comment by porthole-ascend-cinnamon** [comment]
Правильний шлях репозиторію - ghcr.io/porthole-ascend-cinnamon/mhddos_proxy
