### ISSUE TITLE
No working proxies.

### ISSUE THREAD

**Issue by swanter20** [porthole-ascend-cinnamon/mhddos_proxy#161]
When I run the script it gives an error that there are no working proxies and I can't attack with --itarmy what am I doing wrong? By the command python runner.py --itarmy -t 8000 --copies auto
![put2](https://user-images.githubusercontent.com/107597158/173980282-a2fb4270-d135-4382-bf63-4d2ea6979459.png)

**Comment by porthole-ascend-cinnamon** [comment]
Could you provide the screenshot of the start with command line prompt and command visible?

**Comment by swanter20** [comment]
![p2](https://user-images.githubusercontent.com/107597158/174045511-d2632c30-1a6c-4693-a347-e0e6d4fb2762.png)
![p1](https://user-images.githubusercontent.com/107597158/174045566-7e9c934f-5487-4f6a-b67f-c43461885193.png)

**Comment by porthole-ascend-cinnamon** [comment]
Please use the original repo/folder name mhddos_proxy as a root folder (follow the installation instruction as provided).
