### ISSUE TITLE
runner.sh can't recover after an error in runner.py

### ISSUE THREAD

**Issue by snegurok** [porthole-ascend-cinnamon/mhddos_proxy#170]
If there is an error in runner.py, runner.sh cannot recover from that. It falls into endless loop, never reaches update code again. It disables fantastic way of unattended working and updates, that it usually gives us.

A patch on the way.

**Comment by porthole-ascend-cinnamon** [comment]
Closed by https://github.com/porthole-ascend-cinnamon/mhddos_proxy/pull/172
