### ISSUE TITLE
Set number of copies

### ISSUE THREAD

**Issue by kondo-lence** [porthole-ascend-cinnamon/mhddos_proxy#175]
Hallo, I have a question. Is there any way to exceed the automatic copy limit ( set with --copies)?

**Comment by porthole-ascend-cinnamon** [comment]
No, there isn't. What's your use-case? How much CPU do you have and how much copies do you want?

**Comment by porthole-ascend-cinnamon** [comment]
I see. Actually, the next update will raise the limit to (CPU - 1), so stay tuned

**Comment by porthole-ascend-cinnamon** [comment]
done

**Comment by kondo-lence** [comment]
Well it work fine, but in the log is: The number of threads has been reduced to 9394 due to the limitations of your system..
