### ISSUE TITLE
Networking hangs on multiple docker container of mhddos_proxy usage

### ISSUE THREAD

**Issue by VHEMaster** [porthole-ascend-cinnamon/mhddos_proxy#179]
Dear Colleagues,

Since June, 22 I'm suspecting an issues with networking hanging if more than one (sometimes even with one) docker containers that are running mhddos_proxy.

Command line: docker run --rm -d --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy

After network hangs, I can not reach the server through SSH. I need to try to connect about ~10-20 times to be able to kill the containers. In the meanwhile, I can not reach other services that are running on the server. Outcoming ping requests are not going through as well and I'm getting an error: ping: sendmsg: Operation not permitted

In "network hang state" each python3 process is taking 8-12% of CPU time.

Configuration of the server: 
Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-121-generic x86_64)
Intel Xeon X3460, 8GB DDR3 ECC

**Comment by VHEMaster** [comment]
![image](https://user-images.githubusercontent.com/52187485/175820739-9c2a3f1c-fad9-4b75-a3b7-62904cba1028.png)

dmesg -T output

**Comment by VHEMaster** [comment]
If to run the following command line, it works the same
docker run --rm -d --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy -t 10000 --copies 8

**Comment by snegurok** [comment]
I wonder what is visible on mhddos_proxy console. But maybe we can solve the issue without knowing that :)
Seems like there is some limit for nf_conntrack at the os level. Could you simply make it higher?
https://support.huaweicloud.com/intl/en-us/trouble-ecs/ecs_trouble_0324.html

**Comment by VHEMaster** [comment]
@snegurok Hi, thanks for answer.

My value was: 262144. I set it to 16777216. Seems like it doesn't hangs now. After 15 mins at least :) I'll let you know about the final result in a few days if it's ok

Thanks :)

**Comment by porthole-ascend-cinnamon** [comment]
Did you consider the possibility that your network is actually not capable of dealing with this level of performance? Start with one copy and 8k threads (don't provide both params!) and see how it goes, iterate increasing copies first (try adding `--copies auto`).

**Comment by VHEMaster** [comment]
Good morning,

The networking doesn't hangs anymore, but network activity is strange:
![image](https://user-images.githubusercontent.com/52187485/176364288-8c1e3a35-b13f-4662-ab64-1b16a64a0a64.png)

As you can see, appending a fix to nf_conntrack helped and the network traffic was ~200Mbps, but later is dropped to ~50Mbps, and rippling. It didn't act this way before 22nd of June and traffic was pretty stable at ~150Mbps.

**Comment by porthole-ascend-cinnamon** [comment]
@VHEMaster Weird network activity pattern is due to one of the scheduling algorithms, we are aware of the issue and will someday deal with it. 
As for the network hanging - I'm not sure how I can help, since it's clearly an system-level problem. It requires a full machine access and a lengthy investigation to **maybe** grasp what is going on. 
Try this (needs to be run after each reboot)

`sysctl -w net.core.somaxconn=32768 && sysctl -w net.ipv4.ip_local_port_range="16384 60999" && sysctl -w net.ipv4.tcp_syn_retries=3 && sysctl -w net.ipv4.tcp_synack_retries=3 && sysctl -w net.ipv4.tcp_tw_reuse=1 && sysctl -w net.ipv4.tcp_window_scaling=1 && sysctl -w net.ipv4.tcp_fin_timeout=1 && sysctl -w net.ipv4.tcp_max_orphans=32768 && sysctl -w net.ipv4.tcp_max_syn_backlog=16384`

Also, when you feel the system is close to dying, run this command and provide the output (needs `apt install net-tools`):
`netstat -an | grep tcp  | awk '{print $6}' | sort | uniq -c
`

**Comment by VHEMaster** [comment]
@porthole-ascend-cinnamon is it correct output if everything is ok? 
![image](https://user-images.githubusercontent.com/52187485/176717074-34c3d008-754a-4523-83a8-adc174ab2123.png)

**Comment by porthole-ascend-cinnamon** [comment]
@VHEMaster Damn, I forgot you are using Docker. Is it an option to switch to plain python? Or try adding --net=host for Docker, otherwise we won't see anything in this output.
If the ddos is running, we want something like the following (a lot of ESTABLISHED and SYN_SENT, few of the others):
```
    403 ESTABLISHED
      2 FIN_WAIT1
      3 LAST_ACK
     11 LISTEN
   2422 SYN_SENT

```

**Comment by VHEMaster** [comment]
@porthole-ascend-cinnamon with plain python I'm getting this:
![image](https://user-images.githubusercontent.com/52187485/176749613-069dd3c0-8a5e-4bc5-873e-0eda518fcd07.png)

Running with --net=host causes this:
![image](https://user-images.githubusercontent.com/52187485/176750350-217b1dfe-f940-487e-81ea-4d022f4c6713.png)

**Comment by porthole-ascend-cinnamon** [comment]
@VHEMaster for python, add `--lang en` . For docker, `--net=host` should come before the image name, `docker run --rm -d --pull always --net=host ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy`

**Comment by porthole-ascend-cinnamon** [comment]
@VHEMaster It's not that `--lang en` is required generally, but your system does not have a UA locale configured. It usually works out of the box for most systems, thus UA is default.
