### ISSUE TITLE
how to use the BOMB method?

### ISSUE THREAD

**Issue by drew-kun** [porthole-ascend-cinnamon/mhddos_proxy#18]
Hi, thanks for this amazing tool.

Could you please explain how to use the BOMB method here?

Currently getting this error:
<img width="619" alt="Screen Shot 2022-03-18 at 2 15 20 PM" src="https://user-images.githubusercontent.com/10493450/159034152-0ee6fea7-8ffe-4245-9416-4027274235c0.png">

So I guess there should be some sort of docker-compose which allows it?

Or maybe some dockerfile changes has to be implemented?

Like here is what it says in the [MHDDoS official Wiki](https://github.com/MHProDev/MHDDoS/wiki/BOMB-method)

```bash
mkdir bombardier_tmp
cd bombardier_tmp
go mod init bombardier_tmp
go mod edit -replace github.com/codesenberg/bombardier=github.com/PXEiYyMH8F/bombardier@78-add-proxy-support
go get github.com/codesenberg/bombardier
cd ..
rm -r bombardier_tmp
```

Please let me know if you got any solution for that, because without it the tool is not fully featured..

**Comment by porthole-ascend-cinnamon** [comment]
There is no support for BOMB method, I don't consider it to be **that** essential - after all, it's only 1 method. Fell free to provide a PR for it's support, ofc.

**Comment by porthole-ascend-cinnamon** [comment]
Bomb method was added to Docker. If you want to use python, you'll have to deal with the correct installation yourself. (need to have `~/go/bin/bombardier`).
