### ISSUE TITLE
Сканування доступних цілей через VPN

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy#186]
При роботі через VPN помітив, що список доступних цілей малий. Без VPN більший (ключ -- vpn не використовую. Просто хочу, щоб трафік йшов на VPN сервер, потім вже на проксі сервери.

Припускаю, що через блок VPN сервісів росією (можливо й на самих цілях), скрипт не може достучатися до цілей. Хоча через проксі ціль буде доступна.

Схоже, що через це частина цілей може залишитися неатакованими взагалі.

Якщо припущення вірне, то варто додати можливість увімкнути більш "розумний" режим скану цілей: спочатку по всьому списку, а потім вже регулярно оновлювати його в залежності вд результатів кожного циклу атаки. Тимчасово вилючати цілі яки буди недоступні, додавати нові, через деякий час знову додавати ті, що були недоступні (можливо вони вже доступні) та так далі.

**Comment by porthole-ascend-cinnamon** [comment]
Добрий день, дякую за ідеї, проте воно не так трохи працює.
Під "недоступністю" мається на увазі DNS resolving + перевірка на список заборонених мереж. Ціль не може заблокувати DNS resolve ні для VPN, ні для якогось іншого IP, бо він відбувається через публічні DNS сервери.

Можуть бути певні нюанси, але в загальному так. Якщо наведете приклад цілі яка зараз так поводиться - подивимося. Вкажіть також який VPN і яка країна.

**Comment by SergeiKDW** [comment]
Можна написати вам на якийсь  e-mail, щоб не палити VPN сервіс? Якщо рашисти читають - збанять сервіс.

**Comment by porthole-ascend-cinnamon** [comment]
@SergeiKDW porthole-ascend-cinnamon@protonmail.com
