### ISSUE TITLE
Вылезает ошибка Mac M1

### ISSUE THREAD

**Issue by DudoMan** [porthole-ascend-cinnamon/mhddos_proxy#20]
![Screenshot_20220319-034137.jpg](https://user-images.githubusercontent.com/21123136/159101984-4da30272-1ff3-47ea-8529-ebba0f193104.jpg)

В чем может быть проблема?

**Comment by DudoMan** [comment]
В чатах видал ребят с такой же проблемой

**Comment by aorel08** [comment]
@DudoMan у вас завеликий параметр -t

**Comment by DudoMan** [comment]
Да нет ---> python3 runner.py https://tvzvezda.ru --debug

**Comment by porthole-ascend-cinnamon** [comment]
Який вивод `python -c 'import multiprocessing; print(multiprocessing.cpu_count())'`? Скоріше за все перевищується системний ліміт кількості потоків на один процес.

**Comment by porthole-ascend-cinnamon** [comment]
Змінено дефолтне значення `-t` - обмежено 4000 потоків, має запрацювати на дефолтних аргументах.
