### ISSUE TITLE
Непонятное кол-во потоков

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#21]
![image](https://user-images.githubusercontent.com/74729549/159126902-c49d7272-e10a-458b-91d2-ba750b5f3ad0.png)

В команде написано вот так:
python3 runner.py https://www.politnavigator.news/ http://www.politnavigator.news/ -t 1000 --http-methods cfb
а по-итогу выбирается 4000...
и так не первый раз, и не только с этим методом атаки, но и с другими

Также предлагаю изменить это:
`threads_per_target = total_threads // len(targets)`

на это
```
if total_threads < 800 and len(targets) <= 3:
    threads_per_target = total_threads
elif (total_threads >= 800 and total_threads <= 2500) and (len(targets) > 3 and len(targets) <= 7):
    threads_per_target = total_threads // (len(targets) // 2)
else:
    threads_per_target = total_threads // len(targets)
```

**Comment by porthole-ascend-cinnamon** [comment]
В документації, в хелпі, і в баннері який виводиться при запуску, чітко вказано що параметр `-t` - це кількість потоків на кожне ядро процесора. Я вважав що так можно підлаштовувати навантаження залежно від системи - дефолтне значення 300 буде давати різну загальну кількість потоків на різних машинах.

Щодо другої пропозиції - ви по суті пропонуєте ігнорувати задану кількість потоків і запускати умовно замість 500 потоків - 1500.  Такого звісно ніхто робити не буде.

**Comment by porthole-ascend-cinnamon** [comment]
Значення параметру `-t` змінено - тепер він задає остаточну загальну кількість потоків. Дефолтне значення все ще залежить від кількості ядер, але за іншою формулою.
