### ISSUE TITLE
ТЕРМІНОВО Помилка MHDDoS оновили файл start.py

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#22]
![image](https://user-images.githubusercontent.com/74729549/159139867-5de30d69-acf3-4caf-879d-febbff2dbeb6.png)
azureuser@ubuntu-west-us:~/mhddos_proxy$ sudo python3 runner.py https://tsargrad.tv/ http://tsargrad.tv/ -t 2000 -p 1200 --rpc 100 --http-methods bypass cfb dgb --debug
Traceback (most recent call last):
  File "runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/home/azureuser/mhddos_proxy/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], str] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length))
                                                                                      ^
SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/74729549/159139886-5b27448f-1e32-4013-a3b3-47f2684a206e.png)

Список змін: https://github.com/MHProDev/MHDDoS/commit/4a3f7ad14ea3e2c7ce99eef33492f442255e68aa

**Comment by porthole-ascend-cinnamon** [comment]
Добрий день, ситуація звісно неприємна, але наразі будемо чекати змін в MHDDoS. Поки що користайтеся Докером, або відкатіть MHDDoS вручну на робочий комміт.

**Comment by avapirev** [comment]
Тоже самое, уже написал коментар в МХДДоС здесь в гитхабе - https://github.com/MHProDev/MHDDoS/issues/280#issuecomment-1073197948

**Comment by porthole-ascend-cinnamon** [comment]
seems to be fixes by MHDDoS

**Comment by alexnest-ua** [comment]
Yes. fixed https://github.com/MHProDev/PyRoxy/commit/897a7653821216ef1f72e0e2d35a3faf5099687c
But u need to reinstall MHDDoS, or make git pull origin main
Also I recommend author to download the original repo(with PyProxy) into your MHDDoS_proxy to prevent such issues
