### ISSUE TITLE
MBP on M1 reboots in some time

### ISSUE THREAD

**Issue by YuriiTiunov** [porthole-ascend-cinnamon/mhddos_proxy#23]
Hello,

I'm running 
`docker run -it --rm ghcr.io/porthole-ascend-cinnamon/mhddos_proxy -t 300 —debug <site>` 
or 
`python3 runner.py <site> `
and my MBP on M1 hung and then reboot in some time.

**Comment by porthole-ascend-cinnamon** [comment]
Since the `-t` meaning was changed, it should be fine now. Try running without providing the `-t`, if it hangs - start with `-t 1000` and increase by 1000 until you find the best value.

**Comment by YuriiTiunov** [comment]
Just run next command:

`yuriitiunov@MacBook-Pro-Yurii ~ % docker run -it --rm ghcr.io/porthole-ascend-cinnamon/mhddos_proxy 193.37.157.24:80 193.37.157.24:443 193.0.214.42:80 193.0.214.42:443 193.0.214.242:25 193.0.214.242:80 193.0.214.242:110 193.0.214.242:443 193.0.214.242:5025 91.213.144.43:80 91.213.144.43:443 213.109.72.155:80 213.109.72.155:443 217.21.220.247:80 217.21.220.247:443 --debug`

my MBP hang and reboot in 5 min. Looks like a BSOD cause of a memory leak.
