### ISSUE TITLE
Doesn't work under ARM 

### ISSUE THREAD

**Issue by Git-Vi** [porthole-ascend-cinnamon/mhddos_proxy#27]
The docker image doesn't work under ARM

**Comment by Git-Vi** [comment]
> Works for me on M1 Air. What error do you get? Also provide the command you run.

 sudo docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest **********************************
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
59bf1c3509f3: Pull complete
07a400e93df3: Pull complete
64052ee245ef: Pull complete
a44d093ad4a5: Pull complete
0381087ee065: Pull complete
754d1f7947b0: Pull complete
282358656716: Pull complete
Digest: sha256:610b0c5f29809244daf01bab781799b89bb9e372323e248391c92d1a01b1741e
Status: Downloaded newer image for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by AndrewPix** [comment]
@Git-Vi You just need to manually build docker image from Dockerfile

**Comment by zhaparoff** [comment]
Meanwhile, it should run perfectly when using python command `python3 runner.py` instead of prebuilt docker image.

**Comment by porthole-ascend-cinnamon** [comment]
Added multi arch build - please check if it's working now.
