### ISSUE TITLE
Feature: Helm chart for kubernetes

### ISSUE THREAD

**Issue by localdotcom** [porthole-ascend-cinnamon/mhddos_proxy#28]
@porthole-ascend-cinnamon, I wrote a Helm chart to deploy mhddos_proxy to Kubernetes. You may to add this to your repo if you wish.
https://github.com/localdotcom/mhddos-proxy-helm

**Comment by porthole-ascend-cinnamon** [comment]
Unfortunately I am not familiar with Helm, but I trust you it works) So I think I'll just add the link to the README.
