### ISSUE TITLE
Feature: Add additional proxy list from file

### ISSUE THREAD

**Issue by Staskkk** [porthole-ascend-cinnamon/mhddos_proxy#29]
The current version once returned me a message, that none working proxies are found from over 27k URLs.
With an additional proxy list, we will be able to add paid proxies or proxies from other sources, which may be beneficial, especially if it will be russian proxies.
The idea is to add the proxies from the file to the proxies downloaded from the URL.
The proxy list from the file can be parsed with the same period as from the URL, so only one additional argument is needed (filename).
It will certainly be useful for me, if it will be helpful for others as well, please let me know in the comments here and I can try to do the Pull Request myself if nobody will be able to do it faster.

**Comment by porthole-ascend-cinnamon** [comment]
If none was working, that's most probably either an issue with your network, or the target was completely down.
As for the idea - I'll consider adding it. Meanwhile, would you consider donating your proxies to the public use? I have a separate repo for proxies scraping, so I can add any secrets to access the list if needed.

**Comment by Staskkk** [comment]
I didn't think about docker, to be honest) For docker support, it's maybe better to have a local URL that will return proxy list from the file, so basically the same feature you already have, just one more URL to download from.
And I, unfortunately, don't have any proxies to share, I've just written a couple of parsers to copy proxies from:
https://hidemy.name/en/proxy-list/?country=RU#list
and 
https://spys.one/proxys/RU/

**Comment by porthole-ascend-cinnamon** [comment]
Those are already included. What do you mean by "local URL"? If it's something hosted at `localhost:80/...`, then Docker still won't be able to access it by default, cause it has it's own loopback interface. If you've meant just "URL", then we have an issue with authentication.

**Comment by porthole-ascend-cinnamon** [comment]
Feature added.
