### ISSUE TITLE
multiarch build  

### ISSUE THREAD

**Issue by rnd49** [porthole-ascend-cinnamon/mhddos_proxy#3]
please make multiarch build for dockerhub (useful for arm based servers)
use command something like this
`docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag portholeascend/mhddos_proxy:latest .`

some explanation of buildx
https://docs.docker.com/buildx/working-with-buildx/

Thanks!

**Comment by porthole-ascend-cinnamon** [comment]
WIll do, thanks for the tip!
