### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by TauzhnyanskiyArtiom** [porthole-ascend-cinnamon/mhddos_proxy#30]
![image](https://user-images.githubusercontent.com/28104582/159573522-1e58a6cd-fc19-4b3c-85bf-b575a6d088a8.png)

**Comment by porthole-ascend-cinnamon** [comment]
It seems like for some reason your system doesn't like the ` symbol. What's your OS/Python version?

**Comment by TauzhnyanskiyArtiom** [comment]
> It seems like for some reason your system doesn't like the ` symbol. What's your OS/Python version?

Ubuntu 20.04.4 LTS
Python 3.8.10

**Comment by porthole-ascend-cinnamon** [comment]
Wow, that's weird, I though it would be some weird Windows issue. Any ideas what causes this? You are the only one I know with such error.

**Comment by TauzhnyanskiyArtiom** [comment]
Maybe, change language log from Ukranian to English

**Comment by porthole-ascend-cinnamon** [comment]
Please use Docker. Accomodating each and every environment is not feasible.
