### ISSUE TITLE
Problem with the text on windows

### ISSUE THREAD

**Issue by dolotokop** [porthole-ascend-cinnamon/mhddos_proxy#31]
After the last update, there was this problem with the text in the terminal on windows:
![Снимок](https://user-images.githubusercontent.com/102203752/159622082-459b2d0d-76bb-4dce-a086-3bf4e160cf8e.JPG)

**Comment by porthole-ascend-cinnamon** [comment]
I see. Well, that's was and MHDDoS update to add colors. I am considering the fork, but I'm not sure yet - we don't want to lose all their updates.

**Comment by Maxssaf** [comment]
test version for windows console. https://github.com/Maxssaf/MHDDoS

**Comment by porthole-ascend-cinnamon** [comment]
I recommend using Docker in most occasions.
