### ISSUE TITLE
Problem with launching when proxy is empty (suggestion for improvement)

### ISSUE THREAD

**Issue by dolotokop** [porthole-ascend-cinnamon/mhddos_proxy#34]
If after checking the proxy list, it is empty, then the program starts an attack without a proxy from the main IP. This is actually a big anonymity problem, when I leave the program running at night, it happens so often. Please make a function (optional) so that the program does not continue the attack when the proxy is empty. It would also be great if it was possible to attack (also optional) without a proxy, as it happens that proxies are already scarce and slow, and with a VPN attack goes well.

**Comment by porthole-ascend-cinnamon** [comment]
Hmm, that's interesting. Could you provide the full output of the cycle when the problem occurs? I thought it shouldn't happen in the latest versions, the program should stop running - are your up-to-date?
I am considering adding a VPN mode, just need some more time.

**Comment by porthole-ascend-cinnamon** [comment]
Added `--vpn` flag
