### ISSUE TITLE
Проксі

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#35]
Поверніть можливість брати проксі зі свого файлу (у мене є наприклад, приватні РУ проксі з паролем, але я не можу їх використати, хоча MHDDoS їх підтримує: https://github.com/MHProDev/MHDDoS/issues/243#issuecomment-1066600371 )
+ немає сенсу робити константе посилання на файл з проксі, де знаходяться константний список проксі, ураховуючи скільки людей їх використовує - вони дуже швидко вмирають

need to fix: https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/a28c724b55d22537f931dde3a0884874f6198504/runner.py#L15

**Comment by porthole-ascend-cinnamon** [comment]
Такої можливості ніколи не було в інтерфейсі, є відкритий ішшью для додавання.

Файл не статичний, розберіться будь ласка спершу ніж коментувати, він оновлюється кожні пів години з понад сотні джерел.

Проксі на жаль і справді вмирають, тому якщо у вас є джерела додаткових проксі - закликаю пожертвувати на загальне використання.

**Comment by alexnest-ua** [comment]
Ось є рос. проксі:
*Сам юзав у криптотемі*
185.181.247.232:5500@W1cbf1:FM2o3zyI2t
46.8.223.161:5500@W1cbf1:FM2o3zyI2t
188.130.142.124:5500@W1cbf1:FM2o3zyI2t
188.130.142.141:5500@W1cbf1:FM2o3zyI2t
109.248.142.74:5500@W1cbf1:FM2o3zyI2t
188.130.137.123:5500@W1cbf1:FM2o3zyI2t
46.8.106.34:5500@W1cbf1:FM2o3zyI2t
109.248.167.216:5500@W1cbf1:FM2o3zyI2t
46.8.157.81:5500@W1cbf1:FM2o3zyI2t
46.8.193.12:5500@W1cbf1:FM2o3zyI2t
188.130.189.224:5500@W1cbf1:FM2o3zyI2t
212.115.49.228:5500@W1cbf1:FM2o3zyI2t
45.81.136.73:5500@W1cbf1:FM2o3zyI2t
77.83.149.33:5500@W1cbf1:FM2o3zyI2t
45.151.145.127:5500@W1cbf1:FM2o3zyI2t
45.135.32.200:5500@W1cbf1:FM2o3zyI2t
193.58.169.151:5500@W1cbf1:FM2o3zyI2t
193.58.169.198:5500@W1cbf1:FM2o3zyI2t
194.156.96.179:5500@W1cbf1:FM2o3zyI2t
45.134.253.167:5500@W1cbf1:FM2o3zyI2t
185.181.247.232:5500@W1cbf1:FM2o3zyI2t
46.8.223.161:5500@W1cbf1:FM2o3zyI2t
188.130.142.124:5500@W1cbf1:FM2o3zyI2t
188.130.142.141:5500@W1cbf1:FM2o3zyI2t
109.248.142.74:5500@W1cbf1:FM2o3zyI2t
188.130.137.123:5500@W1cbf1:FM2o3zyI2t
46.8.106.34:5500@W1cbf1:FM2o3zyI2t
109.248.167.216:5500@W1cbf1:FM2o3zyI2t
46.8.157.81:5500@W1cbf1:FM2o3zyI2t
46.8.193.12:5500@W1cbf1:FM2o3zyI2t
188.130.189.224:5500@W1cbf1:FM2o3zyI2t
212.115.49.228:5500@W1cbf1:FM2o3zyI2t
45.81.136.73:5500@W1cbf1:FM2o3zyI2t
77.83.149.33:5500@W1cbf1:FM2o3zyI2t
45.151.145.127:5500@W1cbf1:FM2o3zyI2t
45.135.32.200:5500@W1cbf1:FM2o3zyI2t
193.58.169.151:5500@W1cbf1:FM2o3zyI2t
193.58.169.198:5500@W1cbf1:FM2o3zyI2t
194.156.96.179:5500@W1cbf1:FM2o3zyI2t
45.134.253.167:5500@W1cbf1:FM2o3zyI2t

**Comment by porthole-ascend-cinnamon** [comment]
Задам ще вам питання які треба вирішити
Файл з проксі локальний чи віддалений?
Якщо локальний, то як бути з Докером - треба монтувати volume щоби добратися до локального файлу, а це вже нетривіально для середнього користувача
Якщо віддалений, то вам доведеться викласти свої проксі у публічний простір, хоча можна прикинутися що посилання на pastebin важко вгадати і воно як ніби "захищене".

**Comment by alexnest-ua** [comment]
Може хоча б цих провайдерів взяти: https://raw.githubusercontent.com/Aruiem234/mhddosproxy/main/proxies_config.json
Там 104 штуки наче. Чи вони вже не актуальні?

**Comment by porthole-ascend-cinnamon** [comment]
@alexnest-ua Усе актуальне з цього списку - використовується

**Comment by alexnest-ua** [comment]
@porthole-ascend-cinnamon  Треба щось думати з проксі, бо 100 робочих то не діло, бо їх сайти блочать на раз два.
спробуйте ще раз передивитися цей список: https://raw.githubusercontent.com/Aruiem234/mhddosproxy/main/proxies_config.json
Або збільшіть timeout до 10-15 секунд...

**Comment by alexnest-ua** [comment]
Або збирати донати та купувати приватні з паролем, благо MHDDoS їх підтримує

**Comment by alexnest-ua** [comment]
Або писати зарубіжним компаніям з продажу проксі-серверів прохання виділити для України по 1000 робочих проксі на тиждень 
Або зробити програму яка буде рандомно генерувати IP:PORT та перевіряти че є він робочим чи ні - Думаю якщо її запустити хоча б на 100 компів, то буде толк

**Comment by porthole-ascend-cinnamon** [comment]
Дивіться, ви все правильно говорите, але займіться будь ласка цим, не треба просто вкидати ідеї і чекати поки хтось це зробить)

Повірте, той список я 10 разів передивлявся, і не тільки цей - усе що працює пішло у вжиток.

Збільшення таймауту це слизька доріжка, буде більше проксі, але вони будуть повільніші, а також перевірка буде відбуватися довше - чи буде від того додатковий еффект - під питанням.

**Comment by alexnest-ua** [comment]
Поверніть тоді, будь ласка параметр --proxy-timeout (але тоді, мабуть, потрібно і у самому MHDDoS щось підшаманити при віправці пакетів на ціль)
Я це все сам намагався зробити, але нічого не вийшло, бо у мене немає тих ресурсів, що є у вас, тому я й пишу вам.
Перевірені сервіси, де я зараз і раніше купував проксі:
https://proxy6.net/order
https://proxyline.net/ceny/
https://www.proxysolutions.net/proxy-services/
Але, на жаль, там обмеження - не більше 3-ох підключенних машин одночасно, але можна зробити code solution, щоб підтримувати ці обмеження, у будь-якому разі це краще ніж не робочі / переблочені проксі 
Також з вільних джерел нарив:
https://proxy-seller.com
https://brightdata.com
https://buyproxies.org
https://www.webshare.io

Думаю люди будуть згодні донатити, щоб покращити ефективність атак (у тому числі і я)

`P.S. Існує 4,294,967,296 IP адрес ;)` думаю навіть 1000 машин вистачить, щоб обробити цей масив інформації за 1-2 тижні, якщо зробити розумний алгоритм, та розподілити навантаження
