### ISSUE TITLE
No lowercase methods

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#38]
runner.py: error: argument --http-methods: invalid choice: 'cfb' (choose from 'GSB', 'DOWNLOADER', 'APACHE', 'BYPASS', 'STRESS', 'NULL', 'CFB', 'GET', 'EVEN', 'AVB', 'POST', 'HEAD', 'PPS', 'SLOW', 'BOT', 'COOKIE', 'DYN', 'OVH', 'XMLRPC', 'CFBUAM')
runner.py: error: argument --http-methods: invalid choice: 'stress' (choose from 'CFBUAM', 'STRESS', 'NULL', 'CFB', 'BOT', 'COOKIE', 'DOWNLOADER', 'EVEN', 'GET', 'POST', 'PPS', 'HEAD', 'BYPASS', 'GSB', 'OVH', 'XMLRPC', 'APACHE', 'DYN', 'SLOW', 'AVB')

For some reason, your script only works with the UPPERCASE lines of methods, translate the lowercase ones into the UPPERCASE ones like this: 
str.upper()
for example:
'SoMe СлОнов'.upper()  # returns SOME СЛОНОВ

This makes really big problems  to those, who doesn`t check the output (many people)

**Comment by OleksandrBlack** [comment]
> 

--http-methods CFB not --http-methods cfb

**Comment by alextatarinov** [comment]
Thanks for the report. It's not that easy, and obviously, I know how to uppercase the string. But I'm gonna fix it.

**Comment by porthole-ascend-cinnamon** [comment]
Thanks for the report. It's not that easy, and obviously, I know how to uppercase the string. But I'm gonna fix it.

**Comment by porthole-ascend-cinnamon** [comment]
Fixed
