### ISSUE TITLE
Додавання проксі

### ISSUE THREAD

**Issue by Ni4ellas** [porthole-ascend-cinnamon/mhddos_proxy#4]
Привіт, якщо в мене е база проксі ( в txt файлі) то як я можу її додати або поділитися ?

**Comment by KarboDuck** [comment]
Як я розумію, найкращій варіант це запропонувати оновлення для файлу https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/main/proxies_config.json

**Comment by porthole-ascend-cinnamon** [comment]
Привіт, так, все вірно! Це справді наразі дуже необхідно, можеш просто скинути список і я оновлю.

**Comment by udjfvnsaoepna** [comment]
А прокси с авторизацией поддерживается?
Есть прокси кацапский мобильный, с ротацией ip каждую минуту
`login:password@ip:port`
Нужно сделать что бы можно было прокси указать один для всех запросов
типа такого
`python3 runner.py http://87.236.16.230:80 --threads 100 --PROXY-HTTP login:password@ip:port`

И желательно сделать поддержку SOCKS тоже --PROXY-SOCKS

**Comment by porthole-ascend-cinnamon** [comment]
@udjfvnsaoepna дякую за фідбек, проте не впевнений що це буде корисно для багатьох користувачів. Основна суть скрипту - не потрібно шукати проксі чи ВПН. Рекомендую в вашому випадку використати чистий MHDDoS і прописати проксі вручну у файл, або будь який інший інструмент на кшталт DDoS-Ripper.
