### ISSUE TITLE
PyRoxy that inherited addiction

### ISSUE THREAD

**Issue by OleksandrBlack** [porthole-ascend-cinnamon/mhddos_proxy#40]
https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/bc88e1b069bc32e3b1d289c8ab4a2a9a82840ff0/requirements.txt#L8

**Comment by porthole-ascend-cinnamon** [comment]
?

**Comment by porthole-ascend-cinnamon** [comment]
pinned version
