### ISSUE TITLE
TypeError: '>' not supported

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#41]
TypeError: '>' not supported between instances of 'NoneType' and 'int'
    self._target(*self._args, **self._kwargs)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
  File "/home/alex/mhddos_proxy/mhddos/start.py", line 1041, in main
  File "/home/alex/mhddos_proxy/mhddos/start.py", line 1041, in main
    if port > 65535 or port < 1:
    if port > 65535 or port < 1
    
    
idk the reason, but here we are...

**Comment by porthole-ascend-cinnamon** [comment]
fixed
