### ISSUE TITLE
Ціль недоступна?

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#45]
https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/c211d7c399a4413b3791fb672c30c697abdaecd0/runner.py#L28

Великий нюанс що, с одного IP ціль може бути недоступна, а з іншого доступна (геозахист і все таке), а враховуючи, що у нас 12 000 проксі, то з якогось ІР вона таки може бути доступна, тому це дуже суперечлива правка

Якщо я неправий - поправте мене

**Comment by porthole-ascend-cinnamon** [comment]
Ціль не резолвиться вашим DNS сервером, проксі тут не грають ролі.

**Comment by alexnest-ua** [comment]
Ну 12 000 це я просто для загальності сказав, але будь-яка N кількість не міняє суті. Ну якщо то так працює, і воно спрацьовує лише коли ціль взагалі ні звідки недоступна, то добре.

**Comment by porthole-ascend-cinnamon** [comment]
Не скільки ціль недоступна, скільки ваш DNS сервер не резолвить URL в IP адресу, але я вже не знаю як то зрозумілою мовою написати.

**Comment by alexnest-ua** [comment]
Тобто якщо мій DNS сервер не резолвить і якщо таки буде запущена атака, то вона матиме нульову ефективність?

**Comment by porthole-ascend-cinnamon** [comment]
Щоб запустити атаку, треба знайти IP адресу. DNS це просто зручність для людей, інтернет працює тільки через IP.
