### ISSUE TITLE
No KeyboardInterupt with docker-image

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#47]
I can't stop the docker attack in any way - Сtrl+С doesn't work, although it works with a regular script.
Have to kill the docker container manually.

**Comment by porthole-ascend-cinnamon** [comment]
Hmm. That may happen, but I haven't encountered that lately. Was it during attack, or proxies check?

**Comment by alexnest-ua** [comment]
It was only during attack, but right now everything seem to be okey
