### ISSUE TITLE
Failed to establish a new connection: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by seladir** [porthole-ascend-cinnamon/mhddos_proxy#48]
Version: latest release at the moment of writing.
System: Ubuntu 20.04
Used command: `python3 runner.py -t 2000 --debug -c https://lookquizru.xyz/paste.txt`
Error:
`start(
  File "runner.py", line 177, in start
    update_proxies(period, targets)
  File "runner.py", line 86, in update_proxies
  File "runner.py", line 72, in download_proxies
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5d081d20a0>: Failed to establish a new connection: [Errno 24] Too many open files'))`

**Comment by porthole-ascend-cinnamon** [comment]
Does it happen on startup or after some time?

**Comment by seladir** [comment]
It happens each time after the first cycle. So, I run the script, it goes from 0% to 99%, and then fails.

**Comment by seladir** [comment]
Seems as a recently added error, I didn't get it yesterday.

**Comment by porthole-ascend-cinnamon** [comment]
Справді є певне перекриття відкритих сокетів між ітераціями - коли запускається наступна, ще не усі сокети закриті з попередньої, звідси і помилка, але серйозного витоку я не спостерігаю, тому low priority. 
Спробуйте розібратися які системні ліміти і підняти їх. Також спостерігайте за кількістю відкритих сокетів `netstat -an  | wc -l`.

**Comment by Red-Eyed** [comment]
Hey there!
I had the same issue, just change `ulimits` of `nofiles` (number of open files)

### docker
```bash
docker run -it --ulimit nofile=1048576:1048576 --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest -c https://raw.githubusercontent.com/SlavaUkraineSince1991/DDoS-for-all/main/targets/targets.txt -t 10000 --http-methods GET POST STRESS
```

### pyton
```bash
ulimit -n 1048576
python3 runner.py -t 10000 --debug -c https://raw.githubusercontent.com/SlavaUkraineSince1991/DDoS-for-all/main/targets/targets.tx
```

**Comment by alexnest-ua** [comment]
But anyway, this problem is still relevant, because not all systems and not all user can solve it using the methods discussed above.
Therefore, we need a code solution from the @porthole-ascend-cinnamon

**Comment by porthole-ascend-cinnamon** [comment]
Well, I need a machine/instructions to reproduce the issue, since it haven't happened for me.

**Comment by porthole-ascend-cinnamon** [comment]
Дещо змінив у системі, можливо допоможе.

**Comment by porthole-ascend-cinnamon** [comment]
Дещо змінив у системі, можливо допоможе.

**Comment by seladir** [comment]
@Red-Eyed, strange, when I checked the current ulimit, I got "unlimited". Does it anyway help to set some particular big value?
I use ubuntu-2vcpu-4gb-intel on Digital Ocean.

**Comment by Red-Eyed** [comment]
> @Red-Eyed, strange, when I checked the current ulimit, I got "unlimited". Does it anyway help to set some particular big value? I use ubuntu-2vcpu-4gb-intel on Digital Ocean.

I didn't try native python.
I run it via docker.  
There is limits in docker, so if you run it via docker it will help.

**Comment by seladir** [comment]
> > @Red-Eyed, strange, when I checked the current ulimit, I got "unlimited". Does it anyway help to set some particular big value? I use ubuntu-2vcpu-4gb-intel on Digital Ocean.
> 
> I didn't try native python. I run it via docker. There is limits in docker, so if you run it via docker it will help.

Oh, my bad. Just typing "ulimit" gives unlimited, but I should have checked it via "ulimit -n" which has 1024 by default. Increased it, so now it's fine and CPU load really dropped.
