### ISSUE TITLE
cannot import name '_psutil_linux' from partially initialized module 'psutil'

### ISSUE THREAD

**Issue by su-hs** [porthole-ascend-cinnamon/mhddos_proxy#5]
I searched issues for more details, but not found related.

I use same string/command as in readme:

```
$ docker run -it --rm portholeascend/mhddos_proxy https://ria.ru https://tass.ru
```

And trace logs are:
```
Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/mhddos_proxy/MHDDoS/start.py", line 35, in <module>
    from psutil import cpu_percent, net_io_counters, process_iter, virtual_memory
  File "/mhddos_proxy/dependencies/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/mhddos_proxy/dependencies/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/mhddos_proxy/dependencies/psutil/__init__.py)
```

A few days, this tool worked for me. But seems, that `:latest`version of image has something bad.

Or I am missing something.

OS MacOS Monterey,
CPU M1, Arch. Darwin arm64 `v21.2.0`:
Docker v20.x - `20.10.11, build dea9396` and later tried after upgrade on `20.10.13, build a224086`
I also have Python v2 and v3, but in this example it's Docker who maintain internal Python dependencies, afaik.

I sure thing, did:
- Restart macOS
- `docker system prune -a --volumes`
and executed again:

```
$ docker run -it --rm portholeascend/mhddos_proxy:latest -t 500 51.254.201.70 54.38.167.251 91.192.102.90 31.172.70.172

Unable to find image 'portholeascend/mhddos_proxy:latest' locally
latest: Pulling from portholeascend/mhddos_proxy

9b3977197b4f: Pull complete 
8d32640a910c: Pull complete 
0350568631f8: Pull complete 
51d8209a22be: Pull complete 
8ea1bf35c6b0: Pull complete 
a302f10b6389: Pull complete 
efc8c61e4542: Pull complete 

Digest: sha256:6f7883233a31ad0862b9656dae8899227ac2ccd8663d93729d2df49eeb06fd7d

Status: Downloaded newer image for portholeascend/mhddos_proxy:latest

Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/mhddos_proxy/MHDDoS/start.py", line 35, in <module>
    from psutil import cpu_percent, net_io_counters, process_iter, virtual_memory
  File "/mhddos_proxy/dependencies/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/mhddos_proxy/dependencies/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/mhddos_proxy/dependencies/psutil/__init__.py)
```

- VPN disabled, enabled doesn't matter, same behavioer.

didn't help.

Слава Україні!

**Comment by porthole-ascend-cinnamon** [comment]
That seems to be the issue with multiarch build someone asked for in another issue. I will try to fix, but probably just revert to single-arch build.

**Comment by porthole-ascend-cinnamon** [comment]
Done. I've removed the mutliarch builds.

**Comment by su-hs** [comment]
@porthole-ascend-cinnamon interesting.
Thanks, I confirm it's fixed now.

But remember I am interested in arm64 also, M1 CPU.

Great work, btw. Thanks.

**Comment by su-hs** [comment]
@porthole-ascend-cinnamon the reason I created this issue - NOT working arm64 on MacOS CPU M1 - u reverted multi arch, and now I pull amd64 Docker image - this works.

But I assume multi arch is designed for that that we can rely on arch we want.

**Comment by us5tt** [comment]
ср, 16 бер. 2022, 17:28 користувач su-hs ***@***.***> пише:
