### ISSUE TITLE
New output

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#51]
Please move back the old output by default, and just add the additional paramater --table for it.
My subscribers think that everything is broken and turn off the attack until I explain to everyone what the problem is ... 

And it also makes it harder to track down issues by scrolling up. 

Also, on free weak Amazon machines, you have to wait until the table is drawn for 5-10 seconds

**Comment by krsh-off** [comment]
I agree with the above. It also makes it harder to process output automatically, e.g. I used to parse the logs every 2 hours and send notifications to Telegram, to see the current targets and make sure that the script is working fine.

**Comment by alexnest-ua** [comment]
I really need the ability to remove the tabular data output, and return to the old one, otherwise I will not be able to track the normal operation of my automatic script: https://github.com/alexnest-ua/auto_mhddos_alexnest (from now it works very incorrectly because it attacks N different targets at the same time and there is no way for them to draw a new table((  )

Or I will have to take the old commit of your repository ...

**Comment by porthole-ascend-cinnamon** [comment]
От блін ви даєте звісно, ніхто ж не обіцяв стабільних аутпут тексту...Ну прийдется я так розумію повернути..

**Comment by porthole-ascend-cinnamon** [comment]
New version is out (docker will be updated soon). Old debug is enabled by default, switch to table is done with --table flag.
