### ISSUE TITLE
Використовувати різні методи в конфіг файлі

### ISSUE THREAD

**Issue by KarboDuck** [porthole-ascend-cinnamon/mhddos_proxy#54]
Чи можливо зробити щоб в config файлі можна було змішувати методи?

Наприклад:
tass.ru STRESS DGB
https://92.38.145.145:443 CFB
tcp://92.53.97.198:53

**Comment by porthole-ascend-cinnamon** [comment]
Можливо усе), але питання в необхідних зусиллях. Ускладниться парсинг цілей, і подальше їх використання (зараз це просто список строк, а треба щось городити). Поки що не в планах. Можете спробувати свої сили і додати PR.

**Comment by KarboDuck** [comment]
Дякую. Нажаль PR не потягну. Зараз робимо так що запускаемо кожну строку [звідси](https://github.com/Aruiem234/auto_mhddos/blob/main/runner_targets) як окрему копію mhddos_proxy. Але увесь output кидає в один термінал, тому не зручно читати.

**Comment by porthole-ascend-cinnamon** [comment]
Ви краще не чіпайте ті методи, я ж уже пояснював адміну щодо CFB і DGB, плюс є в changelog розлоге пояснення що вони не працюють. На мою думку, атака дефолтими параметрами буде ефективніша.

**Comment by alexander-entin** [comment]
Can you please confirm if the config file is re-read before each proxy refresh or not?

Thanks

**Comment by porthole-ascend-cinnamon** [comment]
@alexander-entin It is re-read before each proxy refresh, you are right.
