### ISSUE TITLE
mhddos_proxy  in termux

### ISSUE THREAD

**Issue by Wendors** [porthole-ascend-cinnamon/mhddos_proxy#55]
Add support if possible mhddos_proxy для termux

**Comment by porthole-ascend-cinnamon** [comment]
Ніби я бачив що запускали, а в чому у вас проблема?

**Comment by alexnest-ua** [comment]
> Ніби я бачив що запускали, а в чому саме у вас проблема? Не знайомий взагалі з termux

Термукс це по cуті Linux для Android

Спробуйте ось так:
Установка:
https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_universal.apk

1. apt update && apt upgrade -y

2. pkg install python -y && pkg install rust -y && pkg install git -y

3. pip install --upgrade pip 

4. Тут специфічно в залежності від архітектури процесора. Але виставив вам скажемо так пріоритет, якщо ви не знаєте яка у вас архітектура то пробуйте встановлювати цю зміну перебираючи мій пріоритет до поки встановлення не буде успішним.

Пріоритети:

- aarch64-linux-android

- arm-linux-androideabi

- armv7-linux-androideabi

- i686-linux-android

- thumbv7neon-linux-androideabi

- x86_64-linux-android

export CARGO_BUILD_TARGET={архітектура процесора}

На моєму пристрої команда виглядає так:

export CARGO_BUILD_TARGET=aarch64-linux-android

5. termux-setup-storage

6. cd storage/shared

7. git clone https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git

8. cd mhddos_proxy

9. pip install -r requirements.txt

10. python runner.py https://ria.ru https://tass.ru



Готово тепер після повного закриття термукса щоб попасти в папку з MHDDOS вам потрібно ввести.

cd storage/shared/MHDDoS


Інструкція не моя, тому сам не тестував, за основу взяв ось це: https://telegra.ph/Vstanovlennya-Termux-ta-MHDDOS-na-nogo--Android-70-120-03-14
