### ISSUE TITLE
[ERROR] Proxy Check failed, Your network may be the problem | The target may not be available.

### ISSUE THREAD

**Issue by alexandrostriviany** [porthole-ascend-cinnamon/mhddos_proxy#6]
Привіт.
намагаюсь запустити на інстансі AWS [amzn2-ami-kernel-5.10-hvm-2.0.20220218.1-x86_64-gp2 (ami-00e76d391403fc721)] але що разу вилітає помилка Proxy Check failed, Your network may be the problem | The target may not be available.
на орігенальному mhddos такого не відбувається.
буду вдячний за поради / воркераунди

**Comment by devrvk** [comment]
Доброго дня. Розібрались? Бо зіткнувся з такою ж фігнею...

**Comment by porthole-ascend-cinnamon** [comment]
Привіт, цікаво, більшість логіки реалізована саме в mhddos, тому різниця має бути мінімальна. Надайте будь ласка команди запуску в обох варіантах, і уточніть кількість CPU / RAM.

**Comment by devrvk** [comment]
Запускаю пайтоном, запускаю дефолтною командою(сайт тільки інший), VPN немає, 2 CPU / 16 RAM python3 runner.py https://tvzvezda.ru --debug

**Comment by alexandrostriviany** [comment]
1 cpu / 8 ram (декілька докерів бомбардира тяне добре) без VPN (але можуть бути внутрішні приколи AWS)
docker run --rm portholeascend/mhddos_proxy -t 500 -p 240 --debug --proxy-timeout 5 178.248.236.218:443 
і чому ВПН саме заборонений? чому з ним не працює? можливо проблема саме в перевірці доступних проксі?
`[20:20:31 - INFO] Downloading Proxies form 61 Providers
[20:20:35 - INFO] 23,786 Proxies are getting checked, this may take a while:
[20:20:35 - INFO] 23,786 Proxies are getting checked against 178.248.236.218:443
[20:20:37 - ERROR] Proxy Check failed, Your network may be the problem | The target may not be available.`

**Comment by devrvk** [comment]
Я гадаю , що через деякі проксі не доступні .ru сайти і воно обламується...

**Comment by porthole-ascend-cinnamon** [comment]
Деякі, але ж не всі. У мене таке було тільки коли інтернет пропав, або я забув вимкнути повільний ВПН.

**Comment by porthole-ascend-cinnamon** [comment]
VPN це ще один прошарок на додачу до проксі, в результаті падає швидкість двічі. Якщо хороший платний ВПН то має бути ок, а ті що вже і так завалені іншими ддосами - ні.

**Comment by StadnikSindar** [comment]
Щоб такого не виикало, вказуйте таргет в форматі URL, тобто з протоколом, наприклад замість 178.248.236.218:443

**Comment by alexandrostriviany** [comment]
Проблема на моєму боці
AWS запідозрив мене у атаках, на мило скинули декілька скарг і обмежили швидкість та час доступу у мережу з інстансів
Тобто після старту тачки інтернет працював 5хвилин з низькою швидкістю тому велика кількість проксі не встигала зробити перевірку у той час як на mhddos їх було меньше і чек проходив.

**Comment by Kerber0ss** [comment]
Проблема знову виникла
```
[08:09:43 - INFO] Downloading Proxies form 61 Providers
[08:09:49 - INFO] 24,505 Proxies are getting checked, this may take a while:
[08:09:49 - INFO] 6,127 Proxies are getting checked against 194.85.18.32:80
[08:09:49 - INFO] 6,126 Proxies are getting checked against 194.85.18.32:443
[08:09:49 - INFO] 6,126 Proxies are getting checked against 194.85.18.31:80
[08:09:49 - INFO] 6,126 Proxies are getting checked against 194.85.18.31:443
[08:09:53 - ERROR] Proxy Check failed, Your network may be the problem | The target may not be available.
```

**Comment by porthole-ascend-cinnamon** [comment]
@Kerber0ss 
І справді, дякую за репорт! Дивно як я раніше цього не помітив, незабаром виправлю.

**Comment by porthole-ascend-cinnamon** [comment]
Готово

**Comment by Kerber0ss** [comment]
Працює, дякую.
