### ISSUE TITLE
[Errno 24] No file descriptors available

### ISSUE THREAD

**Issue by bulletvullet** [porthole-ascend-cinnamon/mhddos_proxy#61]
I am running docker with `docker run --rm -it [ghcr.io/porthole-ascend-cinnamon/mhddos_proxy](http://ghcr.io/porthole-ascend-cinnamon/mhddos_proxy) -t 2000 https://url1 https://url2`
```
/mhddos_proxy/mhddos/files/referers.txt
/mhddos_proxy/mhddos/files/proxies/proxies.txt
```
docker image version
`ghcr.io/porthole-ascend-cinnamon/mhddos_proxy   latest    117cfdec8da8   About an hour ago   138MB`
![image](https://user-images.githubusercontent.com/10546091/161345457-9e1019d0-576d-419c-bc03-33a9c0ca595a.png)

**Comment by porthole-ascend-cinnamon** [comment]
huh, that's weird. try using lower `-t` or restarting docker. You can also add `--ulimit nofile=262144:262144` to the docker command (in the beginning) as an option.

**Comment by akulyhin** [comment]
Доброго дня! будь ласка зв'яжіться зі мною в особистому. Я із Айті армії. Потрібна невеличка допомога по Вашому ПО. https://t.me/ddosukraine_sp Дякую!

**Comment by porthole-ascend-cinnamon** [comment]
should be fixed in the latest version
