### ISSUE TITLE
dns.resolver.NoNameservers: All nameservers failed to answer the query *********.ru

### ISSUE THREAD

**Issue by NikolayMurha** [porthole-ascend-cinnamon/mhddos_proxy#62]
Коли виникає помилка такшталт:
dns.resolver.NoNameservers: All nameservers failed to answer the query *********.ru
скрипт падає

**Comment by porthole-ascend-cinnamon** [comment]
Додав перехоплення усіх dns.Exceptions, дякую за репорт.
