### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rawenloft** [porthole-ascend-cinnamon/mhddos_proxy#64]
After last morning not starting at all with following error:

> Traceback (most recent call last):
  File "/home/kali/mhddos_proxy/runner.py", line 20, in <module>
    from mhddos.start import logger, Methods, bcolors as cl, main as mhddos_main, Tools
  File "/home/kali/mhddos_proxy/mhddos/start.py", line 24, in <module>
    from cloudscraper import create_scraper
ModuleNotFoundError: No module named 'cloudscraper'

Waiting for your instructions! Слава Україні!

**Comment by ppokyd** [comment]
```
pip install -r requirements.txt
```
should solve that issue

**Comment by rawenloft** [comment]
Strange behavior, after git pull / pip install -r requirements.txt not affecting cloudscrapper, was forced to completely delete and re-install repo. Case closed
