### ISSUE TITLE
Are massive proxied attacks any good?

### ISSUE THREAD

**Issue by alexander-entin** [porthole-ascend-cinnamon/mhddos_proxy#65]
UPD. Хотел задать пару конкретных вопросов, а получилось такое, простите.
Подскажите, где это может быть более уместно.
----------------------

Когда атакующих 100500, а рабочих прокси 200, для жертвы это выглядит, как 200 флудящих IP.
Интенсивность флуда с каждого IP высокая, поэтому эти IP легко выделить и заблокировать. 
То же касается и VPN, и Tor

Для эффективной атаки нужно много IP, каждый из которых флудит не слишком сильно, чтобы их было трудно отличить от реальных пользователей.

Если эти рассуждения верны, возникают вопросы:
1. Надо ли рекламировать mhddos_proxy, если массовость только снижает эффективность (легко выделить и заблокировать proxy IP)?

2. Из регионов, которые не заблокированы полностью, может быть лучше атаковать напрямую, тогда эти IP добавятся к 200 прокси и распределенность увеличится? Тогда всем, кто только может, следует атаковать с cloud/VPS. Сделать instance rotation было бы вообще шикарно. А proxy/vpn/tor оставить остальным.

3. Разрозненным сообществам, которые каждое атакует свои цели, хорошо бы объединиться и всем работать по _общему и большому_ списку целей одновременно. Тогда интенсивность атаки одной цели с _одного_ IP снизится (что затруднит защиту), а интенсивность атаки каждой цели с _многих_ IP увеличится

4. Интенсивность атаки _одной цели с одно IP_ следует ограничивать. Надо подумать, как это сделать в случае с proxy/vpn/tor. 

5. На ум сразу приходят slow attacks. К сожалению, Cloudflare отлично защищает от классической slow-headers атаки, просто буферизуя запросы. Но, кажется, slow-read буферизовать нельзя, потому, что перестанут работать приложения, использующие long polling. А какой вариант slow attack в mhddos?

6. Надо закидать Cloudflare петициями, чтоб перестали обслуживать нелюдей.

**Comment by porthole-ascend-cinnamon** [comment]
Дякую за розгорнутий аналіз, я більш-менш в курсі того всього, тому і додав режим VPN, і просив адмінів рекомендувати таку опцію (який власне можна використовувати і без VPN, просто з виділенного сервера). Думаю можна трохи змінити банер щоби вона була більш явною. 

Я працюю над тим щоби проксі було більше, але треба вирішити багато технічних моментів, в мене просто не вистачає часу. Насправді робочих проксі є біля 8000, але чекер на кліенті дуже перебірливий - потрібне нове рішення (роздача пачки проксі зі списку перевірений кожному кліенту), на реалізацію якого треба час.

На жаль, я ледве встигаю займатися технічною стороною, тому на соціальну часу точно не буде. Ідея з великим списком цілей справді непогана, вона певною мірою вирішує питання 4. Щодо обмеження інтенсивності є проблема з фізичним обмеженням - якщо є X проксі, Y цілей, і Z користувачів, то ми ніяк не можемо обмежити трафік без відключення частини користувачів, як мені здається.

Щодо slow атак - на жаль не зовсім у моїй компетенції, я більше по автоматизації, а реалізація атак на боці MHDDoS.
 
Cloudflare уже ніби пару раз намагалися в Інтернет війсках давити, не вийшло, я тут безсилий.

**Comment by porthole-ascend-cinnamon** [comment]
Hi @ddosukraine_sp

**Comment by localdotcom** [comment]
@alexander-entin 
>>Сделать instance rotation было бы вообще шикарно
У мена на AWS в каждой из availability зон трафик ходит через NAT c Elastic IP (static IP). Настроил смену IP каждые пару часов по крону. Вы это имели ввиду, instance rotation для смены IP?
