### ISSUE TITLE
can`t start new thread / Не вдалося запустити усі N потоків

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#69]
![image](https://user-images.githubusercontent.com/74729549/161572764-a29e1659-c913-495b-b4c0-4b5a10b67edb.png)

![image](https://user-images.githubusercontent.com/74729549/161572848-283432af-20cb-4443-9378-ac6f4f4e2558.png)

*From Subscribers*
We need to not just terminate the process when such errors occur, but reduce the number of threads -t to the maximum possible and run attack

**Comment by porthole-ascend-cinnamon** [comment]
Fixed?

**Comment by alexnest-ua** [comment]
Fixed :)
