### ISSUE TITLE
Очищення консолі

### ISSUE THREAD

**Issue by MayborodaYuriy** [porthole-ascend-cinnamon/mhddos_proxy#70]
Коли я натискаю мишкою кудись всередині консолі, то виділяється символ в який я натиснув. Якщо після цього відбудеться очищення консолі для перемальовування таблиці, то все зникне, але не виведеться нового тексту. Буде просто чорне вікно, допоки не натисну Esc чи стрілки.
Хотілося б, щоб при оновленні таблиці якось автоматично виходило з режиму виділення.

**Comment by porthole-ascend-cinnamon** [comment]
Скоріше за все, це не можливо (очистити ваше виділення), у всякому разі мені невідомо. В далеких планах є зміна механізму виводу, але ще не скоро, і не факт що допоможе. 
Вперше чую про таку проблему, якщо чесно, звучить дуже дивно.
