### ISSUE TITLE
Обмеження кількості запитів через VPN

### ISSUE THREAD

**Issue by MayborodaYuriy** [porthole-ascend-cinnamon/mhddos_proxy#71]
Якщо використовувати проксі сервери, то значенням `-rpc` можна коригувати кількість запитів за секунду.
Якщо вказати прапорець `--vpn`, то кількість запитів не залежить від значення `-rpc`. Не можливо зменшити чи збільшити навантаження.

Прошу додати можливість коригування кількості запитів за секунду при використанні VPN.

**Comment by porthole-ascend-cinnamon** [comment]
Значення rpc ніяким чином не обмежує кількість запитів на секунду, це внутрішня кухня і більшості користувачів воно не потрібне. Навантаження ви можете регулювати параметром `-t`.
