### ISSUE TITLE
The app is stoped with issue after a cycle is ended 

### ISSUE THREAD

**Issue by johnbunky** [porthole-ascend-cinnamon/mhddos_proxy#73]
Environment: Mac Hight Sierra

Steps:
python3 runner.py https://alfabank.ru  --http-methods GET STRESS -t 400 --rpc 1000 -p 1200 --debug

Actual result: 
![photo_2022-04-05 21 58 11](https://user-images.githubusercontent.com/11347106/161848118-4be37cc4-37ae-4901-8683-1bbea2d3473f.jpeg)

**Comment by porthole-ascend-cinnamon** [comment]
Що ж, схоже що все що може ламатися - робить це :)
А якщо серйозно, у вас якась побита мережа, усього 10 проксі знайшло...Ну і не спрацював резолвінг айпі-адреси гітхабу.
Перевірте що у вас з коннектом, чи може запущено паралельно іще атаки - це не бажано.

**Comment by johnbunky** [comment]
Thanks for the answer.
My internet connection is ok and I run only one session, that enough, you know.
let me update the actual result:
![image](https://user-images.githubusercontent.com/11347106/162029563-01ba6abf-2a24-4f41-83cd-8c75799c80d3.png)

**Comment by porthole-ascend-cinnamon** [comment]
retries and caching added
