### ISSUE TITLE
Add ability to disable targets in the config file

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#74]
For example, I have such list:
https://biggeek.ru
https://biggeek.ru/catalog/apple-iphone
tcp://79.137.128.191:993
tcp://79.137.128.191:995

And during the attack, my target closed the port or died, so I don't want to spend any more resources on it, and I want to temporarily do this:
https://biggeek.ru
https://biggeek.ru/catalog/apple-iphone
#tcp://79.137.128.191:993
#tcp://79.137.128.191:995

And finally, the program should attack only the following targets:
https://biggeek.ru
https://biggeek.ru/catalog/apple-iphone

Thanks

**Comment by porthole-ascend-cinnamon** [comment]
added
