### ISSUE TITLE
Вичерпано ліміт потоків системи

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#75]
![image](https://user-images.githubusercontent.com/74729549/162482461-0acbd4f9-da6c-4559-a2b7-92edd106a7ce.png)

Давайте стартанемо хоч з одним потоком може?

**Comment by porthole-ascend-cinnamon** [comment]
Мінімальна кількість потоків для роботи - 30. `-` у кінці було додано випадково.
