### ISSUE TITLE
fix Новий цикл через: 2 секунд

### ISSUE THREAD

**Issue by 462vasa** [porthole-ascend-cinnamon/mhddos_proxy#78]
Новий цикл через: 2 секунд 
програма попада у вічний цикл

[15:24:13 - INFO] Новий цикл через: 2 секунд
[15:24:13 - INFO] Кількість проксі: 473

курсор мигае

docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest     GET STRESS -t 5000 --rpc 2000 -p 1200 --debug

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162584795-bf832082-e70e-4392-865f-30c656926f51.png)

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162584818-c0c5068d-70ed-476d-84b9-2acab67fa70c.png)

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162584837-00c194e4-4745-4ae3-bee4-de0f90de080f.png)

**Comment by porthole-ascend-cinnamon** [comment]
Не до кінця розумію проблему, але спробуйте менший -t

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162584865-45e8c837-d7c0-4ada-9938-94bd934cb71e.png)

**Comment by 462vasa** [comment]
cat /proc/cpuinfo| grep "processor"|wc -l
12

**Comment by porthole-ascend-cinnamon** [comment]
Надана команда як мінімум не запускається. Надайте повний лог щоб було видно в чому проблема

**Comment by 462vasa** [comment]
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
stepping	: 7
microcode	: 0x71a
cpu MHz		: 3709.986
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 6400.11
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by 462vasa** [comment]
компютер не висить

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162585026-b73d53fd-55e0-40a8-8d28-806245187b2f.png)

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162585062-4d1761a0-836c-485b-80a5-007d287e947b.png)

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162585090-cb769323-48d6-4fb7-bb49-b1ad46c7fe23.png)

**Comment by 462vasa** [comment]
docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied

**Comment by 462vasa** [comment]
без змин
[15:24:13 - INFO] Новий цикл через: 2 секунд
[15:24:13 - INFO] Кількість проксі: 473

**Comment by porthole-ascend-cinnamon** [comment]
Хз що у вас відбувається, спробуйте останню версію, там дещо змінилося

**Comment by 462vasa** [comment]
[15:24:13 - INFO] Новий цикл через: 2 секунд
[15:24:13 - INFO] Кількість проксі: 473
^C[03:40:20 - INFO] Завершуємо роботу...

пробую

**Comment by 462vasa** [comment]
eroor docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
fix
apt-get install containerd=1.3.3-0ubuntu2
apt-get install docker.io
sudo apt install docker docker-compose docker-doc docker-registry docker.io
пробую

**Comment by 462vasa** [comment]
systemctl start docker

**Comment by 462vasa** [comment]
[05:33:30 - INFO] Новий цикл через: 31 секунд
[05:33:48 - INFO] Кількість проксі: 199

**Comment by 462vasa** [comment]
це нова версия

**Comment by 462vasa** [comment]
![image](https://user-images.githubusercontent.com/46903788/162605984-64e8d851-0243-480b-a8da-4e56333fa589.png)

**Comment by porthole-ascend-cinnamon** [comment]
Я не розумію по вашим двом строчкам в чому проблема - це нормальний вивід. Після них немає нічого, чи як? Спробуйте все-ж таки менший -t, можливо висить докер, а не уся система.

**Comment by 462vasa** [comment]
1. в мене 12 ядер . Програма подає в якийсь вічний цикл. або неможе перейти далі . .2 Нічого не висить. 
![image](https://user-images.githubusercontent.com/46903788/162610065-8286fac9-b786-4739-b766-cb23b0580e0f.png)
на фото видно контрал це -працює. Все обновив що можна . sudo apt install docker docker-compose docker-doc docker-registry docker.io .
3. Режим дебугера або логування  є :

4. цю помилку ловлю покия  Навшой DEV 


Devops

**Comment by 462vasa** [comment]
ттреба переписати логину 
[07:22:06 - INFO] Новий цикл через: 238 секунд
[07:22:14 - INFO] Кількість проксі: 197

стоить

**Comment by 462vasa** [comment]
[07:22:06 - INFO] Новий цикл через: 238 секунд
[07:22:14 - INFO] Кількість проксі: 197

стоит курсор  мигает . Скільки часу пройшло порахуй . миж цими повидомленнями  ХХХ
