### ISSUE TITLE
Зависання при оновленні конфігу

### ISSUE THREAD

**Issue by MayborodaYuriy** [porthole-ascend-cinnamon/mhddos_proxy#79]
Іноді при завантаженні конфігу скрипт, нібито, зависає:
![image](https://user-images.githubusercontent.com/12708401/162798783-066dc0b9-b293-443d-9411-f5f87b547072.png)
Таблиця не оновлюється, `Ctrl+C` виконання не зупиняє.
Якісь запити скрипт продовжує робити, але не зрозуміло які:
![image](https://user-images.githubusercontent.com/12708401/162799471-d3a57984-2a56-491e-82f1-00988b504ff9.png)
![image](https://user-images.githubusercontent.com/12708401/162799554-7bde37af-b7c2-41d8-b62a-551f13b1a8aa.png)

**Comment by SLDay** [comment]
В мене теж завісає програма коли я залишаю ії увімкнутою більш ніж на 24 години (перевіряв на 5 компьютерах з Windows). Але це трапляється тільки з параметром --table. Інший параметр --debug працює без нарекань.

**Comment by sshscp** [comment]
також  починаючи з 09.04  дана проблема актуальна...  іноді репродюситься  за 1-2 цикли... іноді скрипт може працювати декілька годин.... OS  ( ubuntu / Kali ) - репродюситься на всіх...  скрипт ( lasest master from 13-04-2022)....  Коли підлипає - CPU USE 0%

 Threads Dump  ( процесу що залип )

[dump.txt](https://github.com/porthole-ascend-cinnamon/mhddos_proxy/files/8481136/dump.txt)

**Comment by SergeiKDW** [comment]
Думаю, в мене схожа проблема, тому додам сюди.

Ubuntu 21.10, оновлена. Випробувам на Ubuntu 22.04 LTS, останні білди з оновленнями - аналогічно. На Win11 - аналогічно.

![1](https://user-images.githubusercontent.com/103589427/163242734-1e4f1c81-cc78-401b-bc70-df67e4d5a91d.jpg)

Відчуття таке, что робота скрипта ніби затухає. Ніби не оновлює дані. Повідомлення що оновлення через пару секунд так і залишається. Трафік майже зупиняється. На скріні нулі, але в горі там є сервери з трафіком. Але системний монітор показує що його нема.

Як вирішую. Ctrl-C. Запуск команди заново. І все взлітає. 

![2](https://user-images.githubusercontent.com/103589427/163242779-da76ea82-26c0-494a-9d63-05898ace067b.jpg)

Працює якийсь час (3-8 годин) і знову.

Тож запустити та забути надовго нажаль поки що неможливо. Завдання виконуються не ефективно, обладнання простоює.

**Comment by porthole-ascend-cinnamon** [comment]
Усім дякую за данні, візьмемо в пріорітет.

**Comment by SergeiKDW** [comment]
Додам, через Докер під Убунту - аналогічно.

**Comment by porthole-ascend-cinnamon** [comment]
@sshscp дуже дякую за dump, зразу стало видно де проблема. підкажете як таке зробити на майбутне мені? фікс скоро буде залито, тільки протестую

**Comment by porthole-ascend-cinnamon** [comment]
так, ну має працювати тепер думаю)

**Comment by sshscp** [comment]
Вибачте, пізно побачив....
@[porthole-ascend-cinnamon](https://github.com/porthole-ascend-cinnamon)  для дампу використовував - 'pyrasite'  
requirements
 - gdb  (use apt-get to install )
 - python3-dbg (use apt-get to install )
 - pyrasite module  (install via pip  + root priviledges)

Usage
sudo pyrasite {PID} my_dump.py  
 викинe  thread dump  в  std....   в мому кейсі то був nohup.out
