### ISSUE TITLE
Збільшення навантаження на CPU при відсутності мережі

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy#82]
Різко збільшується навантаження на максімум. Звичайний режим 20-40% в залежності від ядра.

![1](https://user-images.githubusercontent.com/103589427/163246297-cd78cfaf-8ff5-499c-aa7f-16474bdda406.jpg)

Через деякий навантаження падає. Бачимо таки картину, 8 секунд залишаєтся значно більше 8 сек:

![2](https://user-images.githubusercontent.com/103589427/163246312-9bf02661-658d-4e05-8587-b27b87a3434b.jpg)

І потім повідомлення:

![3](https://user-images.githubusercontent.com/103589427/163246530-e04dde63-bc09-4008-987e-a2641a62798b.jpg)

Коливання на графіках, то запуск та робота з додатковою программою (для скріншотів).

**Comment by porthole-ascend-cinnamon** [comment]
на останній версії проблема залишається?

**Comment by SergeiKDW** [comment]
Так

**Comment by porthole-ascend-cinnamon** [comment]
остання версія має виправити проблему. якщо ні - зменшуйте параметр `-t`
