### ISSUE TITLE
[Feature request] Додати прапорці для автоматичного завантаження цілей для різних рівнів атак L4(TCP) та L7(HTTP)

### ISSUE THREAD

**Issue by GrisGreyler** [porthole-ascend-cinnamon/mhddos_proxy#83]
Прошу додати прапорці для автоматичного завантаження цілей для різних рівнів атак L4(TCP) та L7(HTTP) як це зроблено для L4 прапорцем __--itarmy__
Наприклад: 
__--itarmy4__
__--itarmy7__
Це значно полегшить використання як для існуючих так і для нових користувачів, які постійно просять готовий рядок з цілями.

**Comment by porthole-ascend-cinnamon** [comment]
wontfix, використвовуйте просто прапорець --itarmy
