### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy#88]
Після оновлень 18.04 з’явилась помилка.

![2](https://user-images.githubusercontent.com/103589427/163891851-d400f219-fbb5-457b-93f0-c436889c107c.png)

**Comment by porthole-ascend-cinnamon** [comment]
Помилка пропала? Скоріше за все був невалідний файл конфігурації в it army.

**Comment by SergeiKDW** [comment]
Останнім часом не повторювалась. Було 1 раз. Але навряд чи через файл. Перезапуск - і працювало.

Було би добре, щоб скрипт не вилітав і не зупинявся. Вивів повідомлення про суть помилки та продовжив перевіряти оновлення файлу. Тож була би автономність та більше ефективність. Не знаю скільки він не працював через зупинку. Бажано щоб юзерам не треба було його контролювати та перезапускати. Не у всіх є стільки часу.
