### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by esurov** [porthole-ascend-cinnamon/mhddos_proxy#91]
При спробі запуска крешиться:

docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest -c https://lookquizru.xyz/paste.txt --table
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:58f6535ee1555b2214f14358a9580f5af93ead25bea63b5add6754b06f6e2118
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest

- Навантаження (кількість потоків) - параметр `-t 3000`, за замовчуванням - CPU * 1000
- Статистика у вигляді таблиці або тексту - прапорець `--table` або `--debug`
- Повна документація - https://github.com/porthole-ascend-cinnamon/mhddos_proxy

        Щоб використовувати VPN або власний IP замість проксі - додайте прапорець `--vpn`

[06:34:28 - INFO] Завантажено конфіг https://lookquizru.xyz/paste.txt на 175 цілей
Traceback (most recent call last):
  File "/mhddos_proxy/./runner.py", line 199, in <module>
    start(init_argparse().parse_args())
  File "/mhddos_proxy/./runner.py", line 157, in start
    targets = list(targets_iter)
  File "/mhddos_proxy/src/targets.py", line 78, in __iter__
    yield Target.from_string(target)
  File "/mhddos_proxy/src/targets.py", line 35, in from_string
    url = URL(Target.prepare_url(parts[0]))
  File "/mhddos_proxy/dependencies/yarl/_url.py", line 151, in __new__
    val = urlsplit(val)
  File "/usr/local/lib/python3.10/urllib/parse.py", line 484, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

**Comment by MayborodaYuriy** [comment]
Теж зіткнувся з цією помилкою. Але якщо файл на комп'ютер та вказати в скриті локальний файл, а не з інтернету, то атака починається.

**Comment by MayborodaYuriy** [comment]
Адреса "https://lookquizru.xyz/paste.txt" захищена CloudFlare. Тому завантажується не файл з цілями, а html сторінка. Відповідно скрипт ламається.

**Comment by porthole-ascend-cinnamon** [comment]
проблема має вирішуватися на стороні адмінів
