### ISSUE TITLE
Possibly separate outgoing and incoming traffic (and packets) into separate values

### ISSUE THREAD

**Issue by KarboDuck** [porthole-ascend-cinnamon/mhddos_proxy#93]
As I understand mhddos_proxy displays outgoing and incoming traffic combined. Consider splitting that value? Total value might be misleading sometimes. For example, 26000 packets/s might be a good value for outgoing traffic, but when in reality 9000 of those packets are incoming, thats a different picture.

`vnstat -l` is used to monitor traffic in screenshot

![image](https://user-images.githubusercontent.com/53382906/164889353-29ed01b8-a5ba-44fa-9035-2eade3133220.png)

**Comment by porthole-ascend-cinnamon** [comment]
We are only measuring outgoing packets and traffic. Due to the nature of most attacks implementation, incoming traffic is not being read.
