### ISSUE TITLE
Increase cpu load

### ISSUE THREAD

**Issue by 6db6a4f0** [porthole-ascend-cinnamon/mhddos_proxy#94]
On my machine I have noticed a significant increase cpu load for the last few days. I had to reduce the -t parameter from 2000 to 1000 to achieve a similar cpu load. The change occurred in the release around April 24.

Are you not noticing the same problem? Is it a bug? Or is it a feature? :)

**Comment by porthole-ascend-cinnamon** [comment]
Depends on what happened with network traffic
If it’s still fine (same on 1000 threads as it was on 2000), = it is a feature
ideally, you have to compare both versions on same targets

**Comment by SergeiKDW** [comment]
In Ukrainian:

Теж саме. Також вимушений був зменшувати -t в декілька разів. Думаю, цілі прилетіли інші і на них почались навантаження. Це добре, що такі цілі, але чи можна додати функцію, яка буде коригувати -t автоматично, якщо потрібно? Наприклад увімкнено завжди, але можно вимкнути додавши відповідний флаг.

Проблема в тому, що ти налагодив, приблизно знаєшь навантаження і думаєш, що так і буде. А потім вого збільшується майже до 100%. Машина починає фрізитися. Часом приходилось робити hard reset, бо на Ctrl-C скрипт не реагує. Вимушений витрачти час на додатковий контроль та перезапуск.

Особливо, коли задачі виконуються на машинах (сервера) де паралельно працюють інші сервіси. Ти можешь виділити частину ресурсу, але без шкоди сервісам. Тож зараз нажаль важко передбачити, що буде з сервером, якщо змінятся цілі, або скрипт збільшить навантадження з інших причин. Немає автономності та автоматизації. Тож і неможливо безпечно запустити та "забути".

Було б добре, щоб навантаження будо більш кероване автоматично. Так більше людей зможе виділити частину ресурсів для задач. Максимальна автоматизація - це добре, більше людей зможуть приєднатися до завдань.

Можливо цим можна керувати через налаштування в ОС. Використовую Ubuntu, Windows Server. Буду вдячний за поради.

**Comment by porthole-ascend-cinnamon** [comment]
@SergeiKDW це цікава думка, але скоріше за все має вирішуватися на один рівень вище - через запуск процесу з обмеженням ресурсів (cpu affinity). Наразі ведеться робота над асинхронною версією - використання ресурсів має впасти. Динамічне керування навантаженням з середини процесу - звучить дуже складно, але якщо є ідеї - робіть PR (тільки дочекайтеся коли асинхронна версія вийде)

**Comment by 6db6a4f0** [comment]
Hi,

I did a simple test, and the CPU load didn't increase with the new versions. The differences in load were in the order of percentages. That's good news.

But it's as @SergeiKDW  writes, the load depends on other influences, like the number and type of targets and their current state. I have similar problems with appropriate load settings, wall as @SergeiKDW.

I will try to solve it with some simple script that will monitor the CPU load and change the -t parameter if necessary.

Anyway, good work, thanks for it...
