### ISSUE TITLE
Флаги VPN

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy#96]
Чудово, що в оновлені з’явилась можливість міксувати VPN з проксі.

Є пропозиція:
--vpn 100 не дуже зрозуміло. Що означає 100? Це 100%?
Планується можливість задавати % співвідношення проксі та VPN?

Пропоную зробити біль наглядніше та зрозуміліше, особливо для початковців та звичайних юзері:
--vpn100 змітити на --vpn-only (або --vpnonly, --vpn_only, краще всі якщо хтось помилився) - тобто тільки через VPN

--vpn - для режиму додавання VPN до прокси. Або --add-vpn (addvpn, add_vpn).

**Comment by porthole-ascend-cinnamon** [comment]
Так, опціональна цифра після прапорця - це відсотки. Були розглянуті різні варіанти, зупинилися на цьому, змінювати не плануємо. "Особливо для початковців та звичайних юзерів" - варто просто додати прапорець `--vpn`. Режим 100% трохи частіше ніж завжди перейде в нулі через 2-3 хвилини атаки, тому не рекомендований для загалу. Ну а той хто знає що робить - той розбереться.

**Comment by SergeiKDW** [comment]
Добре. Дякую за ваш труд!

Чим простіше та зрозуміліше буде скрипт у користуванні, тим нище поріг входу, щоб люди могли приєднатися та зробити атаки більш ефективними. Я б не розраховував, що "хто знає - розбереться". Якщо ще знань недостатньо - просто пару разів спробують та відмовляться. А це не в наших загальних цілях. Бувають цілі для яких треба більше учасників. Тож краще зробити простіше, щоб початківці теж могли допомогти і ім також було просто користуватися. Так можна швидко маштабуватися.
