### ISSUE TITLE
Не знайдено жодної цілі

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy#98]
Скрипт видав помилку та зупинив роботу. Сьогодні вранці помітив. Ввечері вчора було ок.

Зробіть, будь-ласка, обробку помилки, щоб скрипт не зупиняв роботу, а чекав оновлення списку.

Ще в назві файлу помилка: mhddos написано як "mhdos".

![Снимок экрана от 2022-05-02 09-27-39](https://user-images.githubusercontent.com/103589427/166289073-8c270f99-3d6e-4acd-836f-6e9013db8638.png)

![Снимок экрана от 2022-05-02 09-27-02](https://user-images.githubusercontent.com/103589427/166289114-749bc77d-ee49-4dbe-9ab2-266e837dfb30.png)

**Comment by porthole-ascend-cinnamon** [comment]
Ідея огбгорнути увесь скрипт у try/except і перезапускати основний тред у випадку помилки, але а) там використовується exit() і весь процес миттєво виходить б) варто дочекатися асинхронної версії, бо воно буде по-іншому працювати

**Comment by 0xffiber** [comment]
> Зробіть, будь-ласка, обробку помилки, щоб скрипт не зупиняв роботу, а чекав оновлення списку.

Це не просто помилка, це Segmentation fault. Таку помилку неможливо спіймати в try/catch бо це не помилка в скрипті (або в самому cpython, або у c-шних лібах що використовуються).

**Comment by porthole-ascend-cinnamon** [comment]
в новій версії помилки перезавантаження конфігу не впливають на роботу
